#!/bin/bash
# Ask to join the validator set.
#
# Usage: 02-apply-to-join.sh
# Configure with the environment, because these values go on a permanent public
# record and are worth typing deliberately rather than as positional arguments:
#
#   MONIKER=banque-nationale \
#   CONTACT="ops@banque-nationale.example  +221 33 000 0000" \
#   ENTITY_ID="LEI:5493001KJTIIGC8Y1R12" \
#   OWNER_ID="Republic of Senegal" \
#   JURISDICTION=SN \
#   ./02-apply-to-join.sh
#
# This is an application, not a joining. Somebody with standing then puts it to
# governance, and only after it passes does `create-validator` work — the ante
# handler rejects it before it is even processed otherwise.
set -euo pipefail

BIN=${BIN:-/opt/yamale/bin/blockchaind}
HOME_DIR=${BLOCKCHAIND_HOME:-$HOME/.blockchain}
KEY=${OPERATOR_KEY:-validator}

MONIKER="${MONIKER:?set MONIKER}"
CONTACT="${CONTACT:?set CONTACT — a real way to reach you; it is how governance asks questions before voting}"
ENTITY_ID="${ENTITY_ID:?set ENTITY_ID — the LEI or registration number of the legal entity operating this validator}"
OWNER_ID="${OWNER_ID:?set OWNER_ID — who ultimately controls that entity}"
JURISDICTION="${JURISDICTION:?set JURISDICTION — ISO 3166-1 alpha-2, e.g. SN}"

CHAIN_ID=$($BIN status --home "$HOME_DIR" 2>/dev/null |
  python3 -c 'import json,sys; print(json.load(sys.stdin)["node_info"]["network"])')

# Refused rather than created. A missing operator key means the ceremony has not
# been run, and `keys add` here is how a chain ends up with the key that signs
# its blocks generated by a one-line command and its mnemonic printed to a
# terminal nobody was reading.
if ! $BIN keys show "$KEY" --keyring-backend file --home "$HOME_DIR" >/dev/null 2>&1; then
  echo "error: no operator key '$KEY' in the file keyring." >&2
  echo >&2
  echo "  ceremony validator --name \"$MONIKER\" --armor operator.asc" >&2
  echo "  $BIN keys import $KEY operator.asc --keyring-backend file --home $HOME_DIR" >&2
  exit 1
fi

# Refused if this node has not caught up. An application from a node that has
# never kept up asks the set to take on faith the one thing it could have
# demonstrated.
CATCHING_UP=$($BIN status --home "$HOME_DIR" 2>/dev/null |
  python3 -c 'import json,sys; print(json.load(sys.stdin)["sync_info"]["catching_up"])')
if [ "$CATCHING_UP" != "False" ]; then
  echo "error: this node is still catching up. Let it finish first — being seen to have" >&2
  echo "       kept up is the argument you are bringing to the vote." >&2
  exit 1
fi

cat <<INFO

=== applying to join $CHAIN_ID ===

  moniker      $MONIKER
  contact      $CONTACT
  entity       $ENTITY_ID
  owner        $OWNER_ID
  jurisdiction $JURISDICTION

The last three are the declaration, and they are the reason this is not just a
moniker. Concentration on this chain is bounded by arithmetic rather than by
anyone having to refuse a government: per entity, per beneficial owner and per
jurisdiction, checked every epoch. That only works if these are true, so they go
on a permanent public record signed by your own key — the chain cannot detect a
false declaration, it makes one documented and actionable.

You will be asked to re-attest periodically. A declaration that has gone stale
is visible as stale, which is the point: ownership changes quietly, and nothing
in an admission process triggers when it does.

INFO

read -r -p "Submit this application? [y/N] " confirm
case "$confirm" in [yY]*) ;; *) echo "not submitted"; exit 1 ;; esac

$BIN tx validatorgov apply-validator \
  "$MONIKER" "$CONTACT" "$ENTITY_ID" "$OWNER_ID" "$JURISDICTION" \
  --from "$KEY" --chain-id "$CHAIN_ID" \
  --keyring-backend file --home "$HOME_DIR" \
  --fees 500uyml --yes --output json |
  python3 -c '
import json, sys
r = json.load(sys.stdin)
print("broadcast code:", r.get("code"), "txhash:", r.get("txhash"))
if r.get("code"):
    print("raw log:", (r.get("raw_log") or "")[:400])
'

cat <<'NOTE'

A code of 0 means the transaction was ACCEPTED, not that it succeeded. Confirm
it executed:

  blockchaind query tx <txhash>
  blockchaind query validatorgov list-validator-application

Then somebody with standing puts MsgApproveValidator to governance. Only the
governance module may sign that message, so it cannot be self-served. After it
passes:

  blockchaind query validatorgov list-approved-validator
  blockchaind tx staking create-validator validator.json --from validator \
    --keyring-backend file

Keep your self-bond a minority of the set while you are being tested. If the
existing validators still hold more than two thirds, the chain keeps producing
blocks when your node drops — which, on a home connection, it will.
NOTE
