/**
 * Denominations, and the conversion between what the chain stores and what a
 * person reads.
 *
 * The chain deals exclusively in base units — `12500000uyml` — because integer
 * arithmetic is the only kind that is safe for money. People deal exclusively
 * in display units — `12.5 YML`. Every conversion between the two happens here
 * and nowhere else, so there is exactly one place where a factor-of-a-million
 * mistake could live.
 */

export interface DenomInfo {
  /** The base denom the chain stores, e.g. `uyml`. */
  base: string;
  /** The unit people read, e.g. `YML`. */
  symbol: string;
  /** Decimal places between base and display. */
  exponent: number;
  /** Full name, for tooltips and metadata pages. */
  name: string;
  /**
   * Decimal places the currency is quoted in by the people who use it — 2 for
   * the naira's kobo, 0 for the CFA franc, which has no subunit in practice.
   *
   * Distinct from `exponent`, which is how the chain stores it. Everything on
   * this chain is held in millionths so a fee or an interest accrual has room
   * to be exact; this is what an interface rounds to when it prints one.
   * Absent means "print what exponent gives you", which is right for the
   * native token and wrong for a franc.
   */
  minorUnits?: number;
}

/**
 * Denoms the chain knows about at genesis. Anything else — an IBC voucher, a
 * newly registered stablecoin — is resolved at runtime from x/bank's denom
 * metadata, which x/stablecoin publishes when governance approves an issuer.
 */
export const KNOWN_DENOMS: Record<string, DenomInfo> = {
  uyml: { base: 'uyml', symbol: 'YML', exponent: 6, name: 'Yamale' },
  uusd: { base: 'uusd', symbol: 'USD', exponent: 6, name: 'US Dollar' },
  // The remittance stablecoins. Distinct from uusd/ueur above, which are
  // plain fiat units: these are the tokens a corridor actually settles in,
  // so a wallet that cannot name them shows a bare denom on the one screen
  // where somebody is sending money home.
  uusdc: { base: 'uusdc', symbol: 'USDC', exponent: 6, minorUnits: 2, name: 'USD Coin' },
  ueurc: { base: 'ueurc', symbol: 'EURC', exponent: 6, minorUnits: 2, name: 'Euro Coin' },
  uchf: { base: 'uchf', symbol: 'CHF', exponent: 6, name: 'Swiss Franc' },
  ueur: { base: 'ueur', symbol: 'EUR', exponent: 6, name: 'Euro' },
  ugbp: { base: 'ugbp', symbol: 'GBP', exponent: 6, name: 'Pound Sterling' },
  ujpy: { base: 'ujpy', symbol: 'JPY', exponent: 6, minorUnits: 0, name: 'Japanese Yen' },

  // Every ISO 4217 currency in use on the African continent: 42 codes for 54
  // countries, since XOF and XAF each cover a monetary union. Generated by
  // `make currencies-ts` from tools/currencies, which is also what seeds them
  // into genesis — a display registry that disagreed with what the chain mints
  // is how a balance ends up rendered in base units.
  uaoa: { base: 'uaoa', symbol: 'AOA', exponent: 6, minorUnits: 2, name: 'Angolan Kwanza' },
  ubif: { base: 'ubif', symbol: 'BIF', exponent: 6, minorUnits: 0, name: 'Burundian Franc' },
  ubwp: { base: 'ubwp', symbol: 'BWP', exponent: 6, minorUnits: 2, name: 'Botswana Pula' },
  ucdf: { base: 'ucdf', symbol: 'CDF', exponent: 6, minorUnits: 2, name: 'Congolese Franc' },
  ucve: { base: 'ucve', symbol: 'CVE', exponent: 6, minorUnits: 2, name: 'Cape Verdean Escudo' },
  udjf: { base: 'udjf', symbol: 'DJF', exponent: 6, minorUnits: 0, name: 'Djiboutian Franc' },
  udzd: { base: 'udzd', symbol: 'DZD', exponent: 6, minorUnits: 2, name: 'Algerian Dinar' },
  uegp: { base: 'uegp', symbol: 'EGP', exponent: 6, minorUnits: 2, name: 'Egyptian Pound' },
  uern: { base: 'uern', symbol: 'ERN', exponent: 6, minorUnits: 2, name: 'Eritrean Nakfa' },
  uetb: { base: 'uetb', symbol: 'ETB', exponent: 6, minorUnits: 2, name: 'Ethiopian Birr' },
  ughs: { base: 'ughs', symbol: 'GHS', exponent: 6, minorUnits: 2, name: 'Ghanaian Cedi' },
  ugmd: { base: 'ugmd', symbol: 'GMD', exponent: 6, minorUnits: 2, name: 'Gambian Dalasi' },
  ugnf: { base: 'ugnf', symbol: 'GNF', exponent: 6, minorUnits: 0, name: 'Guinean Franc' },
  ukes: { base: 'ukes', symbol: 'KES', exponent: 6, minorUnits: 2, name: 'Kenyan Shilling' },
  ukmf: { base: 'ukmf', symbol: 'KMF', exponent: 6, minorUnits: 0, name: 'Comorian Franc' },
  ulrd: { base: 'ulrd', symbol: 'LRD', exponent: 6, minorUnits: 2, name: 'Liberian Dollar' },
  ulsl: { base: 'ulsl', symbol: 'LSL', exponent: 6, minorUnits: 2, name: 'Lesotho Loti' },
  ulyd: { base: 'ulyd', symbol: 'LYD', exponent: 6, minorUnits: 3, name: 'Libyan Dinar' },
  umad: { base: 'umad', symbol: 'MAD', exponent: 6, minorUnits: 2, name: 'Moroccan Dirham' },
  umga: { base: 'umga', symbol: 'MGA', exponent: 6, minorUnits: 2, name: 'Malagasy Ariary' },
  umru: { base: 'umru', symbol: 'MRU', exponent: 6, minorUnits: 2, name: 'Mauritanian Ouguiya' },
  umur: { base: 'umur', symbol: 'MUR', exponent: 6, minorUnits: 2, name: 'Mauritian Rupee' },
  umwk: { base: 'umwk', symbol: 'MWK', exponent: 6, minorUnits: 2, name: 'Malawian Kwacha' },
  umzn: { base: 'umzn', symbol: 'MZN', exponent: 6, minorUnits: 2, name: 'Mozambican Metical' },
  unad: { base: 'unad', symbol: 'NAD', exponent: 6, minorUnits: 2, name: 'Namibian Dollar' },
  ungn: { base: 'ungn', symbol: 'NGN', exponent: 6, minorUnits: 2, name: 'Nigerian Naira' },
  urwf: { base: 'urwf', symbol: 'RWF', exponent: 6, minorUnits: 0, name: 'Rwandan Franc' },
  uscr: { base: 'uscr', symbol: 'SCR', exponent: 6, minorUnits: 2, name: 'Seychellois Rupee' },
  usdg: { base: 'usdg', symbol: 'SDG', exponent: 6, minorUnits: 2, name: 'Sudanese Pound' },
  usle: { base: 'usle', symbol: 'SLE', exponent: 6, minorUnits: 2, name: 'Sierra Leonean Leone' },
  usos: { base: 'usos', symbol: 'SOS', exponent: 6, minorUnits: 2, name: 'Somali Shilling' },
  ussp: { base: 'ussp', symbol: 'SSP', exponent: 6, minorUnits: 2, name: 'South Sudanese Pound' },
  ustn: { base: 'ustn', symbol: 'STN', exponent: 6, minorUnits: 2, name: 'São Tomé and Príncipe Dobra' },
  uszl: { base: 'uszl', symbol: 'SZL', exponent: 6, minorUnits: 2, name: 'Swazi Lilangeni' },
  utnd: { base: 'utnd', symbol: 'TND', exponent: 6, minorUnits: 3, name: 'Tunisian Dinar' },
  utzs: { base: 'utzs', symbol: 'TZS', exponent: 6, minorUnits: 2, name: 'Tanzanian Shilling' },
  uugx: { base: 'uugx', symbol: 'UGX', exponent: 6, minorUnits: 0, name: 'Ugandan Shilling' },
  uxaf: { base: 'uxaf', symbol: 'XAF', exponent: 6, minorUnits: 0, name: 'Central African CFA Franc' },
  uxof: { base: 'uxof', symbol: 'XOF', exponent: 6, minorUnits: 0, name: 'West African CFA Franc' },
  uzar: { base: 'uzar', symbol: 'ZAR', exponent: 6, minorUnits: 2, name: 'South African Rand' },
  uzmw: { base: 'uzmw', symbol: 'ZMW', exponent: 6, minorUnits: 2, name: 'Zambian Kwacha' },
  uzwg: { base: 'uzwg', symbol: 'ZWG', exponent: 6, minorUnits: 2, name: 'Zimbabwe Gold' },
};

const LP_DENOM_PREFIX = 'amm/pool/';

/** Reports whether a denom represents liquidity-pool shares rather than an asset. */
export function isPoolShare(denom: string): boolean {
  return denom.startsWith(LP_DENOM_PREFIX);
}

/** Extracts the pool id from a share denom, or null if it is not one. */
export function poolIdFromDenom(denom: string): number | null {
  if (!isPoolShare(denom)) return null;
  const id = Number(denom.slice(LP_DENOM_PREFIX.length));
  return Number.isInteger(id) ? id : null;
}

/**
 * Resolves a denom to its display information.
 *
 * Unknown denoms are shown as-is rather than hidden or guessed at. Inventing an
 * exponent would misstate an amount by orders of magnitude, which is far worse
 * than showing a raw unit somebody can look up.
 */
export function resolveDenom(denom: string, registry: Record<string, DenomInfo> = KNOWN_DENOMS): DenomInfo {
  const known = registry[denom];
  if (known) return known;

  const poolId = poolIdFromDenom(denom);
  if (poolId !== null) {
    return { base: denom, symbol: `Pool ${poolId} shares`, exponent: 0, name: `Liquidity shares in pool ${poolId}` };
  }

  if (denom.startsWith('ibc/')) {
    return { base: denom, symbol: `IBC ${denom.slice(4, 10)}…`, exponent: 0, name: 'Transferred asset' };
  }

  return { base: denom, symbol: denom, exponent: 0, name: denom };
}

/**
 * Converts a base-unit amount to its display value as a string.
 *
 * Uses BigInt throughout: balances on this chain routinely exceed what a
 * double can represent exactly, and a rounded balance is a wrong balance.
 */
export function toDisplayAmount(base: string | bigint, exponent: number): string {
  const negative = typeof base === 'string' ? base.trimStart().startsWith('-') : base < 0n;
  let value: bigint;
  try {
    value = typeof base === 'bigint' ? base : BigInt(base.trim());
  } catch {
    return '0';
  }
  if (value < 0n) value = -value;

  const sign = negative ? '-' : '';
  if (exponent <= 0) return sign + value.toString();

  const divisor = 10n ** BigInt(exponent);
  const whole = value / divisor;
  const fraction = value % divisor;

  if (fraction === 0n) return sign + whole.toString();

  // Trim trailing zeros so 12.500000 reads as 12.5, but never round.
  const fractionStr = fraction.toString().padStart(exponent, '0').replace(/0+$/, '');
  return `${sign}${whole.toString()}.${fractionStr}`;
}

/** Groups the integer part with thousands separators for readability. */
export function groupDigits(value: string, locale = 'en-US'): string {
  const [whole, fraction] = value.split('.');
  const negative = whole.startsWith('-');
  const digits = negative ? whole.slice(1) : whole;
  const grouped = Number(digits).toLocaleString(locale, { maximumFractionDigits: 0 });
  const sign = negative ? '-' : '';
  return fraction ? `${sign}${grouped}.${fraction}` : `${sign}${grouped}`;
}

export interface FormatAmountOptions {
  /** Include the symbol, e.g. `12.5 YML`. Defaults to true. */
  withSymbol?: boolean;
  /** Thousands separators. Defaults to true. */
  group?: boolean;
  /** Cap the decimals shown. Values are truncated, never rounded up. */
  maxDecimals?: number;
  registry?: Record<string, DenomInfo>;
}

/**
 * Formats a base-unit amount for a person: `12500000uyml` → `12.5 YML`.
 *
 * Truncates rather than rounds when capping decimals, so a displayed balance is
 * never larger than the real one. Somebody acting on a rounded-up number would
 * find the transaction rejected.
 */
export function formatAmount(
  base: string | bigint,
  denom: string,
  options: FormatAmountOptions = {},
): string {
  const { withSymbol = true, group = true, maxDecimals, registry } = options;
  const info = resolveDenom(denom, registry);

  let display = toDisplayAmount(base, info.exponent);

  // Round to what the currency is actually quoted in, unless the caller asked
  // for something specific. Six decimal places is how the chain stores a
  // balance, not how anybody reads one: 1,359.844414 NGN is a ledger entry,
  // ₦1,359.84 is a price, and a franc printed to six places looks broken to
  // everyone who uses francs.
  const places = maxDecimals ?? info.minorUnits;

  if (places !== undefined && display.includes('.')) {
    const [whole, fraction] = display.split('.');
    const trimmed = fraction.slice(0, places).replace(/0+$/, '');
    display = trimmed ? `${whole}.${trimmed}` : whole;
  }

  if (group) display = groupDigits(display);
  return withSymbol ? `${display} ${info.symbol}` : display;
}

/** A `{denom, amount}` pair as the chain's REST API returns it. */
export interface Coin {
  denom: string;
  amount: string;
}

/** Formats a list of coins as `12.5 YML and 40 USD`, or `nothing` when empty. */
export function formatCoins(
  coins: Coin[] | undefined | null,
  options: FormatAmountOptions = {},
): string {
  if (!coins || coins.length === 0) return 'nothing';
  const parts = coins.map((c) => formatAmount(c.amount, c.denom, options));
  if (parts.length === 1) return parts[0];
  return `${parts.slice(0, -1).join(', ')} and ${parts[parts.length - 1]}`;
}

/** Parses `500uyml` into its parts; returns null when it is not a coin string. */
export function parseCoin(value: string): Coin | null {
  const match = /^(\d+)(.+)$/.exec(value.trim());
  if (!match) return null;
  return { amount: match[1], denom: match[2] };
}
