// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/treasury/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// max_locks_per_treasury bounds how many active locks one treasury may hold.
	// Releasing funds walks a treasury's locks, so an unbounded count would let
	// anyone make that walk arbitrarily expensive.
	MaxLocksPerTreasury uint64 `protobuf:"varint,1,opt,name=max_locks_per_treasury,json=maxLocksPerTreasury,proto3" json:"max_locks_per_treasury,omitempty"`
	// max_role_assignments_per_treasury bounds the size of a treasury's access
	// control list, for the same reason.
	MaxRoleAssignmentsPerTreasury uint64 `protobuf:"varint,2,opt,name=max_role_assignments_per_treasury,json=maxRoleAssignmentsPerTreasury,proto3" json:"max_role_assignments_per_treasury,omitempty"`
	// min_lock_seconds is the shortest duration a lock may run for. A lock that
	// ends the moment it is created commits nothing and only wastes state.
	MinLockSeconds uint64 `protobuf:"varint,3,opt,name=min_lock_seconds,json=minLockSeconds,proto3" json:"min_lock_seconds,omitempty"`
	// max_spend_policy_addresses bounds the combined size of a spend policy's
	// allowlist and blocklist. Both are scanned on every spend and stored
	// indefinitely, so leaving them unbounded would let a treasury make its own
	// payments arbitrarily expensive to validate and bloat state while doing it.
	MaxSpendPolicyAddresses uint64 `protobuf:"varint,4,opt,name=max_spend_policy_addresses,json=maxSpendPolicyAddresses,proto3" json:"max_spend_policy_addresses,omitempty"`
	// fee_operating_treasury_id names the treasury that network fees are paid
	// into on a deployment that has no native token.
	//
	// The destination is a treasury rather than an address because fees are
	// operating income of the deployment, and income that lands in somebody's
	// account is spendable by whoever holds that key. A treasury puts it behind
	// the same roles, spend policies and M-of-N group control as every other
	// committed balance, and leaves the audit trail those produce.
	//
	// Nothing reads this unless route_fees_to_operating_treasury is set.
	FeeOperatingTreasuryId uint64 `protobuf:"varint,5,opt,name=fee_operating_treasury_id,json=feeOperatingTreasuryId,proto3" json:"fee_operating_treasury_id,omitempty"`
	// route_fees_to_operating_treasury turns fee routing on.
	//
	// It is a separate field rather than a zero sentinel on the id above, because
	// in proto3 a uint64 of 0 is indistinguishable from a field nobody set, and
	// whether zero names a treasury is x/treasury's numbering convention rather
	// than this parameter's. Ids start at one today, so zero would work; if that
	// ever changed, every chain that had not configured routing would start
	// paying its fees into whichever treasury was created first, and nothing here
	// would have changed to say so.
	RouteFeesToOperatingTreasury bool `protobuf:"varint,6,opt,name=route_fees_to_operating_treasury,json=routeFeesToOperatingTreasury,proto3" json:"route_fees_to_operating_treasury,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e6e6992f906e895, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxLocksPerTreasury() uint64 {
	if m != nil {
		return m.MaxLocksPerTreasury
	}
	return 0
}

func (m *Params) GetMaxRoleAssignmentsPerTreasury() uint64 {
	if m != nil {
		return m.MaxRoleAssignmentsPerTreasury
	}
	return 0
}

func (m *Params) GetMinLockSeconds() uint64 {
	if m != nil {
		return m.MinLockSeconds
	}
	return 0
}

func (m *Params) GetMaxSpendPolicyAddresses() uint64 {
	if m != nil {
		return m.MaxSpendPolicyAddresses
	}
	return 0
}

func (m *Params) GetFeeOperatingTreasuryId() uint64 {
	if m != nil {
		return m.FeeOperatingTreasuryId
	}
	return 0
}

func (m *Params) GetRouteFeesToOperatingTreasury() bool {
	if m != nil {
		return m.RouteFeesToOperatingTreasury
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "blockchain.treasury.v1.Params")
}

func init() {
	proto.RegisterFile("blockchain/treasury/v1/params.proto", fileDescriptor_0e6e6992f906e895)
}

var fileDescriptor_0e6e6992f906e895 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4f, 0xe2, 0x40,
	0x18, 0xc6, 0xe9, 0xc2, 0x92, 0xcd, 0x1c, 0x36, 0xbb, 0xdd, 0x0d, 0xdb, 0x25, 0x58, 0x11, 0x63,
	0x42, 0x3c, 0xd0, 0x10, 0x4e, 0xfe, 0xb9, 0xe0, 0x81, 0x68, 0x62, 0x22, 0x01, 0x4e, 0x5e, 0x26,
	0x43, 0xfb, 0x52, 0x27, 0x76, 0x66, 0x9a, 0x99, 0x42, 0xda, 0xaf, 0xe0, 0xc9, 0xa3, 0x47, 0x3f,
	0x82, 0x1f, 0xc3, 0x23, 0x47, 0x8f, 0x06, 0x0e, 0xfa, 0x31, 0x4c, 0xa7, 0x56, 0x88, 0x72, 0x99,
	0x4c, 0xde, 0xe7, 0xf9, 0x3d, 0xef, 0x9b, 0x3c, 0x68, 0x77, 0x1c, 0x08, 0xf7, 0xda, 0xbd, 0x22,
	0x94, 0x3b, 0x91, 0x04, 0xa2, 0xa6, 0x32, 0x71, 0x66, 0x6d, 0x27, 0x24, 0x92, 0x30, 0xd5, 0x0a,
	0xa5, 0x88, 0x84, 0x59, 0x59, 0x99, 0x5a, 0xb9, 0xa9, 0x35, 0x6b, 0x57, 0x7f, 0x13, 0x46, 0xb9,
	0x70, 0xf4, 0x9b, 0x59, 0xab, 0x7f, 0x7d, 0xe1, 0x0b, 0xfd, 0x75, 0xd2, 0x5f, 0x36, 0x6d, 0xdc,
	0x15, 0x51, 0xb9, 0xaf, 0x13, 0xcd, 0x0e, 0xaa, 0x30, 0x12, 0xe3, 0x34, 0x50, 0xe1, 0x10, 0x24,
	0xce, 0x03, 0x2d, 0xa3, 0x6e, 0x34, 0x4b, 0x83, 0x3f, 0x8c, 0xc4, 0xe7, 0xa9, 0xd8, 0x07, 0x39,
	0x7a, 0x97, 0xcc, 0x53, 0xb4, 0x93, 0x42, 0x52, 0x04, 0x80, 0x89, 0x52, 0xd4, 0xe7, 0x0c, 0x78,
	0xf4, 0x89, 0xff, 0xa6, 0xf9, 0x2d, 0x46, 0xe2, 0x81, 0x08, 0xa0, 0xbb, 0xb2, 0xad, 0x27, 0x35,
	0xd1, 0x2f, 0x46, 0xb9, 0x5e, 0x8f, 0x15, 0xb8, 0x82, 0x7b, 0xca, 0x2a, 0x6a, 0xf0, 0x27, 0xa3,
	0x3c, 0x5d, 0x3c, 0xcc, 0xa6, 0xe6, 0x11, 0xaa, 0xa6, 0x3b, 0x55, 0x08, 0xdc, 0xc3, 0xa1, 0x08,
	0xa8, 0x9b, 0x60, 0xe2, 0x79, 0x12, 0x94, 0x02, 0x65, 0x95, 0x34, 0xf3, 0x8f, 0x91, 0x78, 0x98,
	0x1a, 0xfa, 0x5a, 0xef, 0xe6, 0xb2, 0x79, 0x80, 0xfe, 0x4f, 0x00, 0xb0, 0x08, 0x41, 0x92, 0x88,
	0x72, 0xff, 0xe3, 0x4a, 0x4c, 0x3d, 0xeb, 0xbb, 0x66, 0x2b, 0x13, 0x80, 0x8b, 0x5c, 0xcf, 0xef,
	0x3b, 0xf3, 0xcc, 0x1e, 0xaa, 0x4b, 0x31, 0x8d, 0x00, 0x4f, 0x00, 0x14, 0x8e, 0xc4, 0x86, 0x10,
	0xab, 0x5c, 0x37, 0x9a, 0x3f, 0x06, 0x35, 0xed, 0xeb, 0x01, 0xa8, 0x91, 0xf8, 0x92, 0x74, 0xb8,
	0xf7, 0x7a, 0xbf, 0x6d, 0xdc, 0xbc, 0x3c, 0xec, 0xd7, 0xd6, 0x2a, 0x8e, 0x57, 0x25, 0x67, 0x7d,
	0x9c, 0x1c, 0x3f, 0x2e, 0x6c, 0x63, 0xbe, 0xb0, 0x8d, 0xe7, 0x85, 0x6d, 0xdc, 0x2e, 0xed, 0xc2,
	0x7c, 0x69, 0x17, 0x9e, 0x96, 0x76, 0xe1, 0xb2, 0x91, 0x10, 0x46, 0x02, 0x70, 0x36, 0xe3, 0x51,
	0x12, 0x82, 0x1a, 0x97, 0x75, 0xbf, 0x9d, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x3f, 0xff,
	0xe4, 0x47, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxLocksPerTreasury != that1.MaxLocksPerTreasury {
		return false
	}
	if this.MaxRoleAssignmentsPerTreasury != that1.MaxRoleAssignmentsPerTreasury {
		return false
	}
	if this.MinLockSeconds != that1.MinLockSeconds {
		return false
	}
	if this.MaxSpendPolicyAddresses != that1.MaxSpendPolicyAddresses {
		return false
	}
	if this.FeeOperatingTreasuryId != that1.FeeOperatingTreasuryId {
		return false
	}
	if this.RouteFeesToOperatingTreasury != that1.RouteFeesToOperatingTreasury {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RouteFeesToOperatingTreasury {
		i--
		if m.RouteFeesToOperatingTreasury {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.FeeOperatingTreasuryId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeOperatingTreasuryId))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxSpendPolicyAddresses != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSpendPolicyAddresses))
		i--
		dAtA[i] = 0x20
	}
	if m.MinLockSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinLockSeconds))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxRoleAssignmentsPerTreasury != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxRoleAssignmentsPerTreasury))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxLocksPerTreasury != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxLocksPerTreasury))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxLocksPerTreasury != 0 {
		n += 1 + sovParams(uint64(m.MaxLocksPerTreasury))
	}
	if m.MaxRoleAssignmentsPerTreasury != 0 {
		n += 1 + sovParams(uint64(m.MaxRoleAssignmentsPerTreasury))
	}
	if m.MinLockSeconds != 0 {
		n += 1 + sovParams(uint64(m.MinLockSeconds))
	}
	if m.MaxSpendPolicyAddresses != 0 {
		n += 1 + sovParams(uint64(m.MaxSpendPolicyAddresses))
	}
	if m.FeeOperatingTreasuryId != 0 {
		n += 1 + sovParams(uint64(m.FeeOperatingTreasuryId))
	}
	if m.RouteFeesToOperatingTreasury {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLocksPerTreasury", wireType)
			}
			m.MaxLocksPerTreasury = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLocksPerTreasury |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRoleAssignmentsPerTreasury", wireType)
			}
			m.MaxRoleAssignmentsPerTreasury = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRoleAssignmentsPerTreasury |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLockSeconds", wireType)
			}
			m.MinLockSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLockSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSpendPolicyAddresses", wireType)
			}
			m.MaxSpendPolicyAddresses = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSpendPolicyAddresses |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeOperatingTreasuryId", wireType)
			}
			m.FeeOperatingTreasuryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeOperatingTreasuryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteFeesToOperatingTreasury", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RouteFeesToOperatingTreasury = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
