// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/constitution/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgProposeAmendment opens an amendment to the invariants.
//
// Amendment is possible at all, rather than forbidden outright, because
// "forbidden" would be a lie. A chain can be hard-forked and an upgrade handler
// can rewrite any store, so a constitution with no amendment path does not
// become unamendable — it relocates its amendments into a binary release, which
// is a change with less public notice and fewer signatures than a proposal. The
// path exists so that it is the cheapest one, and it is made slow and loud so
// that taking it is a thing people find out about.
//
// Two independent conditions, both required: a governance proposal to open it,
// and a supermajority of the voting power recorded at that moment to ratify it,
// with weeks between the two. Neither alone is enough.
type MsgProposeAmendment struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// invariants is the complete replacement set, not a delta. All fields must be
	// supplied and all of them are validated, so an amendment that meant to move
	// one ceiling cannot silently zero another by omitting it — and a zero here
	// would be a divisor or a missing destination somewhere else.
	Invariants Invariants `protobuf:"bytes,2,opt,name=invariants,proto3" json:"invariants"`
	// reason is the stated grounds, in plain words.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgProposeAmendment) Reset()         { *m = MsgProposeAmendment{} }
func (m *MsgProposeAmendment) String() string { return proto.CompactTextString(m) }
func (*MsgProposeAmendment) ProtoMessage()    {}
func (*MsgProposeAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{0}
}
func (m *MsgProposeAmendment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeAmendment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeAmendment.Merge(m, src)
}
func (m *MsgProposeAmendment) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeAmendment proto.InternalMessageInfo

func (m *MsgProposeAmendment) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgProposeAmendment) GetInvariants() Invariants {
	if m != nil {
		return m.Invariants
	}
	return Invariants{}
}

func (m *MsgProposeAmendment) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgProposeAmendmentResponse returns the id of the amendment that was opened.
type MsgProposeAmendmentResponse struct {
	AmendmentId uint64 `protobuf:"varint,1,opt,name=amendment_id,json=amendmentId,proto3" json:"amendment_id,omitempty"`
}

func (m *MsgProposeAmendmentResponse) Reset()         { *m = MsgProposeAmendmentResponse{} }
func (m *MsgProposeAmendmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProposeAmendmentResponse) ProtoMessage()    {}
func (*MsgProposeAmendmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{1}
}
func (m *MsgProposeAmendmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeAmendmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeAmendmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeAmendmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeAmendmentResponse.Merge(m, src)
}
func (m *MsgProposeAmendmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeAmendmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeAmendmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeAmendmentResponse proto.InternalMessageInfo

func (m *MsgProposeAmendmentResponse) GetAmendmentId() uint64 {
	if m != nil {
		return m.AmendmentId
	}
	return 0
}

// MsgRatifyAmendment is one validator agreeing to a pending amendment.
//
// Signed by the operator account, at the weight that operator carries when it
// signs, and countable only once. A validator that changes its mind cannot
// un-ratify: the amendment's protection is the delay and the threshold, not the
// ability to run the vote backwards, and a withdrawable ratification would let
// a set hold an amendment at one vote short indefinitely.
type MsgRatifyAmendment struct {
	// validator is the operator address in its account form.
	Validator   string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	AmendmentId uint64 `protobuf:"varint,2,opt,name=amendment_id,json=amendmentId,proto3" json:"amendment_id,omitempty"`
}

func (m *MsgRatifyAmendment) Reset()         { *m = MsgRatifyAmendment{} }
func (m *MsgRatifyAmendment) String() string { return proto.CompactTextString(m) }
func (*MsgRatifyAmendment) ProtoMessage()    {}
func (*MsgRatifyAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{2}
}
func (m *MsgRatifyAmendment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRatifyAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRatifyAmendment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRatifyAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRatifyAmendment.Merge(m, src)
}
func (m *MsgRatifyAmendment) XXX_Size() int {
	return m.Size()
}
func (m *MsgRatifyAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRatifyAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRatifyAmendment proto.InternalMessageInfo

func (m *MsgRatifyAmendment) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *MsgRatifyAmendment) GetAmendmentId() uint64 {
	if m != nil {
		return m.AmendmentId
	}
	return 0
}

// MsgRatifyAmendmentResponse defines the response structure for executing a
// MsgRatifyAmendment message.
type MsgRatifyAmendmentResponse struct {
}

func (m *MsgRatifyAmendmentResponse) Reset()         { *m = MsgRatifyAmendmentResponse{} }
func (m *MsgRatifyAmendmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRatifyAmendmentResponse) ProtoMessage()    {}
func (*MsgRatifyAmendmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{3}
}
func (m *MsgRatifyAmendmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRatifyAmendmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRatifyAmendmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRatifyAmendmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRatifyAmendmentResponse.Merge(m, src)
}
func (m *MsgRatifyAmendmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRatifyAmendmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRatifyAmendmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRatifyAmendmentResponse proto.InternalMessageInfo

// MsgWithdrawAmendment takes a pending amendment back before it takes effect.
//
// Authority-gated like the proposal, because withdrawing one is a decision of
// the same kind. It exists so that an amendment found to be wrong during its
// own delay can be stopped by the body that opened it, rather than left to run
// its weeks out while everybody waits to see whether it fails to ratify.
type MsgWithdrawAmendment struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority   string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	AmendmentId uint64 `protobuf:"varint,2,opt,name=amendment_id,json=amendmentId,proto3" json:"amendment_id,omitempty"`
}

func (m *MsgWithdrawAmendment) Reset()         { *m = MsgWithdrawAmendment{} }
func (m *MsgWithdrawAmendment) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawAmendment) ProtoMessage()    {}
func (*MsgWithdrawAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{4}
}
func (m *MsgWithdrawAmendment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawAmendment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawAmendment.Merge(m, src)
}
func (m *MsgWithdrawAmendment) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawAmendment proto.InternalMessageInfo

func (m *MsgWithdrawAmendment) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgWithdrawAmendment) GetAmendmentId() uint64 {
	if m != nil {
		return m.AmendmentId
	}
	return 0
}

// MsgWithdrawAmendmentResponse defines the response structure for executing a
// MsgWithdrawAmendment message.
type MsgWithdrawAmendmentResponse struct {
}

func (m *MsgWithdrawAmendmentResponse) Reset()         { *m = MsgWithdrawAmendmentResponse{} }
func (m *MsgWithdrawAmendmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawAmendmentResponse) ProtoMessage()    {}
func (*MsgWithdrawAmendmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c71e420f6000c83, []int{5}
}
func (m *MsgWithdrawAmendmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawAmendmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawAmendmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawAmendmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawAmendmentResponse.Merge(m, src)
}
func (m *MsgWithdrawAmendmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawAmendmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawAmendmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawAmendmentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgProposeAmendment)(nil), "blockchain.constitution.v1.MsgProposeAmendment")
	proto.RegisterType((*MsgProposeAmendmentResponse)(nil), "blockchain.constitution.v1.MsgProposeAmendmentResponse")
	proto.RegisterType((*MsgRatifyAmendment)(nil), "blockchain.constitution.v1.MsgRatifyAmendment")
	proto.RegisterType((*MsgRatifyAmendmentResponse)(nil), "blockchain.constitution.v1.MsgRatifyAmendmentResponse")
	proto.RegisterType((*MsgWithdrawAmendment)(nil), "blockchain.constitution.v1.MsgWithdrawAmendment")
	proto.RegisterType((*MsgWithdrawAmendmentResponse)(nil), "blockchain.constitution.v1.MsgWithdrawAmendmentResponse")
}

func init() {
	proto.RegisterFile("blockchain/constitution/v1/tx.proto", fileDescriptor_6c71e420f6000c83)
}

var fileDescriptor_6c71e420f6000c83 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xce, 0x35, 0x50, 0x29, 0x57, 0x24, 0xa8, 0x89, 0x20, 0x98, 0xca, 0x14, 0x23, 0x55, 0x55,
	0x44, 0x6d, 0x5a, 0xa4, 0x82, 0xba, 0x90, 0x64, 0xeb, 0x10, 0x09, 0xcc, 0x80, 0xc4, 0x52, 0x5d,
	0xe3, 0xe3, 0x72, 0x22, 0xbe, 0x8b, 0xee, 0xbd, 0x86, 0x46, 0x42, 0x02, 0x31, 0x30, 0x30, 0xf1,
	0x33, 0x18, 0x33, 0xf4, 0x47, 0x74, 0xac, 0x98, 0x98, 0x10, 0x4a, 0x86, 0xfc, 0x07, 0x26, 0x64,
	0x3b, 0x71, 0x3e, 0x9c, 0x26, 0x44, 0x5d, 0x2c, 0xdf, 0x73, 0xcf, 0xfb, 0xf1, 0xbc, 0xef, 0x63,
	0xe3, 0x47, 0xc7, 0x0d, 0x59, 0x7b, 0x5f, 0xab, 0x13, 0x2e, 0xdc, 0x9a, 0x14, 0xa0, 0xb9, 0x3e,
	0xd1, 0x5c, 0x0a, 0xb7, 0xb5, 0xeb, 0xea, 0x53, 0xa7, 0xa9, 0xa4, 0x96, 0x86, 0x39, 0x22, 0x39,
	0xe3, 0x24, 0xa7, 0xb5, 0x6b, 0xae, 0x93, 0x80, 0x0b, 0xe9, 0x46, 0xcf, 0x98, 0x6e, 0xee, 0xcc,
	0xc9, 0x39, 0x11, 0x1e, 0xd3, 0xef, 0xd6, 0x24, 0x04, 0x12, 0xdc, 0x00, 0x58, 0xc8, 0x08, 0x80,
	0x0d, 0x2e, 0xee, 0xc5, 0x17, 0x47, 0xd1, 0xc9, 0x8d, 0x0f, 0x83, 0xab, 0x3c, 0x93, 0x4c, 0xc6,
	0x78, 0xf8, 0x16, 0xa3, 0xf6, 0x5f, 0x84, 0x6f, 0x57, 0x81, 0xbd, 0x54, 0xb2, 0x29, 0x81, 0x96,
	0x03, 0x2a, 0xfc, 0x80, 0x0a, 0x6d, 0xec, 0xe3, 0x1c, 0x39, 0xd1, 0x75, 0xa9, 0xb8, 0x6e, 0x17,
	0xd0, 0x26, 0xda, 0xce, 0x55, 0x0a, 0x3f, 0xcf, 0x76, 0xf2, 0x83, 0x94, 0x65, 0xdf, 0x57, 0x14,
	0xe0, 0xb5, 0x56, 0x5c, 0x30, 0x6f, 0x44, 0x35, 0x5e, 0x61, 0xcc, 0x45, 0x8b, 0x28, 0x4e, 0x84,
	0x86, 0xc2, 0xca, 0x26, 0xda, 0x5e, 0xdb, 0xdb, 0x72, 0x2e, 0x1f, 0x86, 0x73, 0x98, 0xb0, 0x2b,
	0xb9, 0xf3, 0xdf, 0x0f, 0x32, 0x3f, 0xfa, 0x9d, 0x22, 0xf2, 0xc6, 0x92, 0x18, 0x77, 0xf0, 0xaa,
	0xa2, 0x04, 0xa4, 0x28, 0x64, 0xc3, 0x3e, 0xbc, 0xc1, 0xe9, 0xa0, 0xf4, 0xa5, 0xdf, 0x29, 0x8e,
	0x4a, 0x7f, 0xeb, 0x77, 0x8a, 0xe3, 0x63, 0x3c, 0x9d, 0x1c, 0xe4, 0x0c, 0x91, 0x76, 0x09, 0xdf,
	0x9f, 0x01, 0x7b, 0x14, 0x9a, 0x52, 0x00, 0x35, 0x1e, 0xe2, 0x1b, 0x64, 0x08, 0x1e, 0x71, 0x3f,
	0x1a, 0xc3, 0x35, 0x6f, 0x2d, 0xc1, 0x0e, 0x7d, 0xbb, 0x83, 0xb0, 0x51, 0x05, 0xe6, 0x11, 0xcd,
	0xdf, 0xb5, 0x27, 0xa6, 0xd7, 0x22, 0x0d, 0xee, 0x13, 0x2d, 0xd5, 0xe2, 0xe9, 0x25, 0xd4, 0x54,
	0xc5, 0x95, 0x54, 0xc5, 0x83, 0x17, 0x91, 0xea, 0x24, 0x24, 0x54, 0xfd, 0x78, 0xae, 0xea, 0xa9,
	0xde, 0xec, 0x0d, 0x6c, 0xa6, 0xd1, 0xa1, 0x66, 0xfb, 0x0c, 0xe1, 0x7c, 0x15, 0xd8, 0x1b, 0xae,
	0xeb, 0xbe, 0x22, 0x1f, 0xae, 0x6e, 0x88, 0xff, 0x90, 0x54, 0x4e, 0x2f, 0xd2, 0x99, 0x2b, 0x29,
	0xd5, 0x9d, 0x6d, 0xe1, 0x8d, 0x59, 0xf8, 0x50, 0xd6, 0xde, 0xd7, 0x2c, 0xce, 0x56, 0x81, 0x19,
	0x1f, 0xf1, 0xad, 0x94, 0xd5, 0xdd, 0x79, 0xf6, 0x9c, 0xe1, 0x0f, 0xf3, 0xd9, 0x92, 0x01, 0x89,
	0xa1, 0xda, 0xf8, 0xe6, 0xb4, 0x53, 0x9c, 0x05, 0xb9, 0xa6, 0xf8, 0xe6, 0xfe, 0x72, 0xfc, 0xa4,
	0xf4, 0x27, 0xbc, 0x9e, 0xde, 0xe9, 0x93, 0x05, 0xc9, 0x52, 0x11, 0xe6, 0xf3, 0x65, 0x23, 0x86,
	0x0d, 0x98, 0xd7, 0x3f, 0x87, 0x1f, 0x76, 0xa5, 0x74, 0xde, 0xb5, 0xd0, 0x45, 0xd7, 0x42, 0x7f,
	0xba, 0x16, 0xfa, 0xde, 0xb3, 0x32, 0x17, 0x3d, 0x2b, 0xf3, 0xab, 0x67, 0x65, 0xde, 0x6e, 0xb5,
	0x49, 0x40, 0x1a, 0xd4, 0xbd, 0x7c, 0xf3, 0xba, 0xdd, 0xa4, 0x70, 0xbc, 0x1a, 0xfd, 0xb8, 0x9e,
	0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x6c, 0x1b, 0x1a, 0x87, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ProposeAmendment opens a change to the invariants and starts its public
	// delay. It is authority-gated, so a proposal is the only way in.
	ProposeAmendment(ctx context.Context, in *MsgProposeAmendment, opts ...grpc.CallOption) (*MsgProposeAmendmentResponse, error)
	// RatifyAmendment records one validator agreeing to a pending amendment.
	RatifyAmendment(ctx context.Context, in *MsgRatifyAmendment, opts ...grpc.CallOption) (*MsgRatifyAmendmentResponse, error)
	// WithdrawAmendment takes a pending amendment back before it takes effect.
	WithdrawAmendment(ctx context.Context, in *MsgWithdrawAmendment, opts ...grpc.CallOption) (*MsgWithdrawAmendmentResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ProposeAmendment(ctx context.Context, in *MsgProposeAmendment, opts ...grpc.CallOption) (*MsgProposeAmendmentResponse, error) {
	out := new(MsgProposeAmendmentResponse)
	err := c.cc.Invoke(ctx, "/blockchain.constitution.v1.Msg/ProposeAmendment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RatifyAmendment(ctx context.Context, in *MsgRatifyAmendment, opts ...grpc.CallOption) (*MsgRatifyAmendmentResponse, error) {
	out := new(MsgRatifyAmendmentResponse)
	err := c.cc.Invoke(ctx, "/blockchain.constitution.v1.Msg/RatifyAmendment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawAmendment(ctx context.Context, in *MsgWithdrawAmendment, opts ...grpc.CallOption) (*MsgWithdrawAmendmentResponse, error) {
	out := new(MsgWithdrawAmendmentResponse)
	err := c.cc.Invoke(ctx, "/blockchain.constitution.v1.Msg/WithdrawAmendment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ProposeAmendment opens a change to the invariants and starts its public
	// delay. It is authority-gated, so a proposal is the only way in.
	ProposeAmendment(context.Context, *MsgProposeAmendment) (*MsgProposeAmendmentResponse, error)
	// RatifyAmendment records one validator agreeing to a pending amendment.
	RatifyAmendment(context.Context, *MsgRatifyAmendment) (*MsgRatifyAmendmentResponse, error)
	// WithdrawAmendment takes a pending amendment back before it takes effect.
	WithdrawAmendment(context.Context, *MsgWithdrawAmendment) (*MsgWithdrawAmendmentResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ProposeAmendment(ctx context.Context, req *MsgProposeAmendment) (*MsgProposeAmendmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeAmendment not implemented")
}
func (*UnimplementedMsgServer) RatifyAmendment(ctx context.Context, req *MsgRatifyAmendment) (*MsgRatifyAmendmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RatifyAmendment not implemented")
}
func (*UnimplementedMsgServer) WithdrawAmendment(ctx context.Context, req *MsgWithdrawAmendment) (*MsgWithdrawAmendmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawAmendment not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ProposeAmendment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeAmendment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeAmendment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.constitution.v1.Msg/ProposeAmendment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeAmendment(ctx, req.(*MsgProposeAmendment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RatifyAmendment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRatifyAmendment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RatifyAmendment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.constitution.v1.Msg/RatifyAmendment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RatifyAmendment(ctx, req.(*MsgRatifyAmendment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawAmendment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawAmendment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawAmendment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.constitution.v1.Msg/WithdrawAmendment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawAmendment(ctx, req.(*MsgWithdrawAmendment))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.constitution.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeAmendment",
			Handler:    _Msg_ProposeAmendment_Handler,
		},
		{
			MethodName: "RatifyAmendment",
			Handler:    _Msg_RatifyAmendment_Handler,
		},
		{
			MethodName: "WithdrawAmendment",
			Handler:    _Msg_WithdrawAmendment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain/constitution/v1/tx.proto",
}

func (m *MsgProposeAmendment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeAmendment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeAmendment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Invariants.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProposeAmendmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeAmendmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeAmendmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AmendmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmendmentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRatifyAmendment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRatifyAmendment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRatifyAmendment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AmendmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmendmentId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRatifyAmendmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRatifyAmendmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRatifyAmendmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawAmendment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawAmendment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawAmendment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AmendmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmendmentId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawAmendmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawAmendmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawAmendmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgProposeAmendment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Invariants.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgProposeAmendmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AmendmentId != 0 {
		n += 1 + sovTx(uint64(m.AmendmentId))
	}
	return n
}

func (m *MsgRatifyAmendment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AmendmentId != 0 {
		n += 1 + sovTx(uint64(m.AmendmentId))
	}
	return n
}

func (m *MsgRatifyAmendmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawAmendment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AmendmentId != 0 {
		n += 1 + sovTx(uint64(m.AmendmentId))
	}
	return n
}

func (m *MsgWithdrawAmendmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgProposeAmendment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeAmendment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeAmendment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invariants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Invariants.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProposeAmendmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeAmendmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeAmendmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmendmentId", wireType)
			}
			m.AmendmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmendmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRatifyAmendment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRatifyAmendment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRatifyAmendment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmendmentId", wireType)
			}
			m.AmendmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmendmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRatifyAmendmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRatifyAmendmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRatifyAmendmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawAmendment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawAmendment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawAmendment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmendmentId", wireType)
			}
			m.AmendmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmendmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawAmendmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawAmendmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawAmendmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
