// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/validatorgov/v1/approved_validator.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ApprovedValidator defines the ApprovedValidator message.
type ApprovedValidator struct {
	Candidate string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Approved  string `protobuf:"bytes,2,opt,name=approved,proto3" json:"approved,omitempty"`
	// declaration is copied from the application at approval and kept current by
	// re-attestation. The epoch check reads it from here rather than from the
	// application, because the application is what was asked for once and this is
	// what is claimed now — and a ceiling has to be computed against the second.
	Declaration Declaration `protobuf:"bytes,3,opt,name=declaration,proto3" json:"declaration"`
}

func (m *ApprovedValidator) Reset()         { *m = ApprovedValidator{} }
func (m *ApprovedValidator) String() string { return proto.CompactTextString(m) }
func (*ApprovedValidator) ProtoMessage()    {}
func (*ApprovedValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d77bad54da1e460, []int{0}
}
func (m *ApprovedValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApprovedValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApprovedValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApprovedValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovedValidator.Merge(m, src)
}
func (m *ApprovedValidator) XXX_Size() int {
	return m.Size()
}
func (m *ApprovedValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovedValidator.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovedValidator proto.InternalMessageInfo

func (m *ApprovedValidator) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

func (m *ApprovedValidator) GetApproved() string {
	if m != nil {
		return m.Approved
	}
	return ""
}

func (m *ApprovedValidator) GetDeclaration() Declaration {
	if m != nil {
		return m.Declaration
	}
	return Declaration{}
}

func init() {
	proto.RegisterType((*ApprovedValidator)(nil), "blockchain.validatorgov.v1.ApprovedValidator")
}

func init() {
	proto.RegisterFile("blockchain/validatorgov/v1/approved_validator.proto", fileDescriptor_9d77bad54da1e460)
}

var fileDescriptor_9d77bad54da1e460 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f,
	0x4a, 0xcf, 0x2f, 0xd3, 0x2f, 0x33, 0xd4, 0x4f, 0x2c, 0x28, 0x28, 0xca, 0x2f, 0x4b, 0x4d, 0x89,
	0x87, 0x4b, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x49, 0x21, 0x34, 0xe9, 0x21, 0x6b, 0xd2,
	0x2b, 0x33, 0x94, 0xd2, 0xc1, 0x63, 0x60, 0x4a, 0x6a, 0x72, 0x4e, 0x62, 0x51, 0x62, 0x49, 0x66,
	0x7e, 0x1e, 0xc4, 0x24, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c, 0x30, 0x53, 0x1f, 0xc4, 0x82, 0x88,
	0x2a, 0xcd, 0x63, 0xe4, 0x12, 0x74, 0x84, 0x5a, 0x1e, 0x06, 0x33, 0x43, 0x48, 0x86, 0x8b, 0x33,
	0x39, 0x31, 0x2f, 0x05, 0xc4, 0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08,
	0x49, 0x71, 0x71, 0xc0, 0xdc, 0x2b, 0xc1, 0x04, 0x96, 0x84, 0xf3, 0x85, 0xfc, 0xb9, 0xb8, 0x91,
	0xac, 0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36, 0x52, 0xd7, 0xc3, 0xed, 0x0b, 0x3d, 0x17, 0x84,
	0x72, 0x27, 0x96, 0x13, 0xf7, 0xe4, 0x19, 0x82, 0x90, 0x4d, 0x70, 0x72, 0x38, 0xf1, 0x48, 0x8e,
	0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58,
	0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xb5, 0xca, 0xc4, 0xdc, 0xc4, 0x9c, 0x54, 0x7d, 0xa4,
	0x50, 0xa8, 0x40, 0x0d, 0x87, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0x4f, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0xae, 0x2a, 0x89, 0x80, 0x01, 0x00, 0x00,
}

func (m *ApprovedValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApprovedValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ApprovedValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Declaration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintApprovedValidator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Approved) > 0 {
		i -= len(m.Approved)
		copy(dAtA[i:], m.Approved)
		i = encodeVarintApprovedValidator(dAtA, i, uint64(len(m.Approved)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Candidate) > 0 {
		i -= len(m.Candidate)
		copy(dAtA[i:], m.Candidate)
		i = encodeVarintApprovedValidator(dAtA, i, uint64(len(m.Candidate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintApprovedValidator(dAtA []byte, offset int, v uint64) int {
	offset -= sovApprovedValidator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ApprovedValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Candidate)
	if l > 0 {
		n += 1 + l + sovApprovedValidator(uint64(l))
	}
	l = len(m.Approved)
	if l > 0 {
		n += 1 + l + sovApprovedValidator(uint64(l))
	}
	l = m.Declaration.Size()
	n += 1 + l + sovApprovedValidator(uint64(l))
	return n
}

func sovApprovedValidator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApprovedValidator(x uint64) (n int) {
	return sovApprovedValidator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ApprovedValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovedValidator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApprovedValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApprovedValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Candidate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Candidate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approved", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approved = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Declaration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovedValidator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Declaration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovedValidator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovedValidator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApprovedValidator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApprovedValidator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovedValidator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApprovedValidator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApprovedValidator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApprovedValidator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApprovedValidator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApprovedValidator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApprovedValidator = fmt.Errorf("proto: unexpected end of group")
)
