// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/validatorgov/v1/concentration.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConcentrationCap is which ceiling a demotion was for. Recorded rather than
// inferred, because "over the entity cap" and "over the jurisdiction cap" are
// different facts about the same validator and the remedy is different for
// each: one entity can be restructured, a jurisdiction cannot.
type ConcentrationCap int32

const (
	// CONCENTRATION_CAP_UNSPECIFIED is the unset default and is never valid.
	CONCENTRATION_CAP_UNSPECIFIED ConcentrationCap = 0
	// CONCENTRATION_CAP_ENTITY is the ceiling on one declared legal entity.
	CONCENTRATION_CAP_ENTITY ConcentrationCap = 1
	// CONCENTRATION_CAP_BENEFICIAL_OWNER is the ceiling on one declared ultimate
	// beneficial owner, across every entity it owns.
	CONCENTRATION_CAP_BENEFICIAL_OWNER ConcentrationCap = 2
	// CONCENTRATION_CAP_JURISDICTION is the ceiling on the power answering to one
	// national authority.
	CONCENTRATION_CAP_JURISDICTION ConcentrationCap = 3
)

var ConcentrationCap_name = map[int32]string{
	0: "CONCENTRATION_CAP_UNSPECIFIED",
	1: "CONCENTRATION_CAP_ENTITY",
	2: "CONCENTRATION_CAP_BENEFICIAL_OWNER",
	3: "CONCENTRATION_CAP_JURISDICTION",
}

var ConcentrationCap_value = map[string]int32{
	"CONCENTRATION_CAP_UNSPECIFIED":      0,
	"CONCENTRATION_CAP_ENTITY":           1,
	"CONCENTRATION_CAP_BENEFICIAL_OWNER": 2,
	"CONCENTRATION_CAP_JURISDICTION":     3,
}

func (x ConcentrationCap) String() string {
	return proto.EnumName(ConcentrationCap_name, int32(x))
}

func (ConcentrationCap) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cee778bb6cd35fc2, []int{0}
}

// Demotion is a validator whose power the epoch check took away, and why.
//
// It is a record and not a punishment. Nothing is slashed, no delegation is
// unbonded, and it is undone automatically at the first epoch the breach has
// cleared — so the entity's remedy is in its own hands and does not require
// anybody to vote on letting it back. That is the difference between a
// concentration ceiling and an expulsion.
type Demotion struct {
	// operator is the address in its account form, matching how the approval
	// allowlist and the rotation records key a validator.
	Operator string           `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Cap      ConcentrationCap `protobuf:"varint,2,opt,name=cap,proto3,enum=blockchain.validatorgov.v1.ConcentrationCap" json:"cap,omitempty"`
	// group is the declared value that breached — the entity id, the owner id or
	// the country code — so the record says which set the validator was counted
	// in rather than only that some ceiling was hit.
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// group_power_bps and cap_bps are what the group held and what it was allowed
	// to hold, at the epoch the demotion happened. Frozen into the record because
	// both figures are recomputed every epoch, and a demotion that could only be
	// explained by numbers that have since moved cannot be audited at all.
	GroupPowerBps   uint64 `protobuf:"varint,4,opt,name=group_power_bps,json=groupPowerBps,proto3" json:"group_power_bps,omitempty"`
	CapBps          uint64 `protobuf:"varint,5,opt,name=cap_bps,json=capBps,proto3" json:"cap_bps,omitempty"`
	DemotedAtHeight int64  `protobuf:"varint,6,opt,name=demoted_at_height,json=demotedAtHeight,proto3" json:"demoted_at_height,omitempty"`
	// jailed_validator records that this demotion is what jailed the validator,
	// so that restoring it un-jails only what it jailed. A validator already
	// jailed for downtime when the epoch check ran must stay jailed when the
	// breach clears: releasing it would turn a concentration ceiling into a way
	// of clearing somebody else's downtime.
	JailedValidator bool `protobuf:"varint,7,opt,name=jailed_validator,json=jailedValidator,proto3" json:"jailed_validator,omitempty"`
}

func (m *Demotion) Reset()         { *m = Demotion{} }
func (m *Demotion) String() string { return proto.CompactTextString(m) }
func (*Demotion) ProtoMessage()    {}
func (*Demotion) Descriptor() ([]byte, []int) {
	return fileDescriptor_cee778bb6cd35fc2, []int{0}
}
func (m *Demotion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Demotion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Demotion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Demotion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demotion.Merge(m, src)
}
func (m *Demotion) XXX_Size() int {
	return m.Size()
}
func (m *Demotion) XXX_DiscardUnknown() {
	xxx_messageInfo_Demotion.DiscardUnknown(m)
}

var xxx_messageInfo_Demotion proto.InternalMessageInfo

func (m *Demotion) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Demotion) GetCap() ConcentrationCap {
	if m != nil {
		return m.Cap
	}
	return CONCENTRATION_CAP_UNSPECIFIED
}

func (m *Demotion) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Demotion) GetGroupPowerBps() uint64 {
	if m != nil {
		return m.GroupPowerBps
	}
	return 0
}

func (m *Demotion) GetCapBps() uint64 {
	if m != nil {
		return m.CapBps
	}
	return 0
}

func (m *Demotion) GetDemotedAtHeight() int64 {
	if m != nil {
		return m.DemotedAtHeight
	}
	return 0
}

func (m *Demotion) GetJailedValidator() bool {
	if m != nil {
		return m.JailedValidator
	}
	return false
}

// ConcentrationGroup is one entity, owner or jurisdiction and what it currently
// holds. It exists for the supervisor's query rather than for the chain: under
// equal seats a ceiling is a count out of a count, and the point of publishing
// it this way is that it can be checked against a list by somebody who is not
// recomputing anything.
type ConcentrationGroup struct {
	Cap      ConcentrationCap `protobuf:"varint,1,opt,name=cap,proto3,enum=blockchain.validatorgov.v1.ConcentrationCap" json:"cap,omitempty"`
	Group    string           `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Power    int64            `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	PowerBps uint64           `protobuf:"varint,4,opt,name=power_bps,json=powerBps,proto3" json:"power_bps,omitempty"`
	CapBps   uint64           `protobuf:"varint,5,opt,name=cap_bps,json=capBps,proto3" json:"cap_bps,omitempty"`
	// over is whether the group is above its ceiling right now, which is not the
	// same as whether anything has been demoted: a breach the set is too small to
	// correct stays reported and uncorrected, because a cap must never be the
	// reason a chain stops producing blocks.
	Over bool `protobuf:"varint,6,opt,name=over,proto3" json:"over,omitempty"`
}

func (m *ConcentrationGroup) Reset()         { *m = ConcentrationGroup{} }
func (m *ConcentrationGroup) String() string { return proto.CompactTextString(m) }
func (*ConcentrationGroup) ProtoMessage()    {}
func (*ConcentrationGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_cee778bb6cd35fc2, []int{1}
}
func (m *ConcentrationGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConcentrationGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConcentrationGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConcentrationGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConcentrationGroup.Merge(m, src)
}
func (m *ConcentrationGroup) XXX_Size() int {
	return m.Size()
}
func (m *ConcentrationGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ConcentrationGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ConcentrationGroup proto.InternalMessageInfo

func (m *ConcentrationGroup) GetCap() ConcentrationCap {
	if m != nil {
		return m.Cap
	}
	return CONCENTRATION_CAP_UNSPECIFIED
}

func (m *ConcentrationGroup) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ConcentrationGroup) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *ConcentrationGroup) GetPowerBps() uint64 {
	if m != nil {
		return m.PowerBps
	}
	return 0
}

func (m *ConcentrationGroup) GetCapBps() uint64 {
	if m != nil {
		return m.CapBps
	}
	return 0
}

func (m *ConcentrationGroup) GetOver() bool {
	if m != nil {
		return m.Over
	}
	return false
}

func init() {
	proto.RegisterEnum("blockchain.validatorgov.v1.ConcentrationCap", ConcentrationCap_name, ConcentrationCap_value)
	proto.RegisterType((*Demotion)(nil), "blockchain.validatorgov.v1.Demotion")
	proto.RegisterType((*ConcentrationGroup)(nil), "blockchain.validatorgov.v1.ConcentrationGroup")
}

func init() {
	proto.RegisterFile("blockchain/validatorgov/v1/concentration.proto", fileDescriptor_cee778bb6cd35fc2)
}

var fileDescriptor_cee778bb6cd35fc2 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xbd, 0x8e, 0xd3, 0x4c,
	0x14, 0xcd, 0xe4, 0x6f, 0xb3, 0x23, 0x7d, 0x5f, 0xcc, 0x28, 0x12, 0x26, 0x80, 0x65, 0x52, 0x44,
	0x66, 0x05, 0xb6, 0x16, 0xa8, 0x11, 0x8e, 0xe3, 0x05, 0x23, 0xe4, 0x44, 0x93, 0x2c, 0x08, 0x1a,
	0x6b, 0x62, 0x8f, 0x1c, 0x43, 0xe2, 0x19, 0xd9, 0xc6, 0xb0, 0x6f, 0x40, 0xc9, 0x3b, 0x20, 0x5a,
	0x2a, 0x1e, 0x02, 0x51, 0xad, 0xa8, 0x28, 0x51, 0xf2, 0x22, 0xc8, 0xe3, 0xb0, 0x64, 0x37, 0x42,
	0x14, 0x74, 0xf7, 0x9e, 0x73, 0xe6, 0xfa, 0x9e, 0x23, 0x5f, 0xa8, 0xcf, 0x16, 0xcc, 0x7f, 0xe5,
	0xcf, 0x49, 0x14, 0x1b, 0x39, 0x59, 0x44, 0x01, 0xc9, 0x58, 0x12, 0xb2, 0xdc, 0xc8, 0x0f, 0x0d,
	0x9f, 0xc5, 0x3e, 0x8d, 0xb3, 0x84, 0x64, 0x11, 0x8b, 0x75, 0x9e, 0xb0, 0x8c, 0xa1, 0xee, 0x6f,
	0xbd, 0xbe, 0xad, 0xd7, 0xf3, 0xc3, 0xee, 0x15, 0x9f, 0xa5, 0x4b, 0x96, 0x7a, 0x42, 0x69, 0x94,
	0x4d, 0xf9, 0xac, 0xdb, 0x09, 0x59, 0xc8, 0x4a, 0xbc, 0xa8, 0x4a, 0xb4, 0xf7, 0xa9, 0x0a, 0x5b,
	0x43, 0xba, 0x64, 0xc5, 0x7c, 0x74, 0x0f, 0xb6, 0x18, 0xa7, 0x49, 0x31, 0x4f, 0x06, 0x2a, 0xd0,
	0xf6, 0x07, 0xf2, 0xb7, 0xcf, 0xb7, 0x3b, 0x9b, 0x31, 0x66, 0x10, 0x24, 0x34, 0x4d, 0x27, 0x59,
	0x12, 0xc5, 0x21, 0x3e, 0x53, 0xa2, 0xfb, 0xb0, 0xe6, 0x13, 0x2e, 0x57, 0x55, 0xa0, 0xfd, 0x7f,
	0xe7, 0x96, 0xfe, 0xe7, 0xed, 0x74, 0x6b, 0xdb, 0x8d, 0x45, 0x38, 0x2e, 0x1e, 0xa2, 0x0e, 0x6c,
	0x84, 0x09, 0x7b, 0xcd, 0xe5, 0x5a, 0xf1, 0x49, 0x5c, 0x36, 0xa8, 0x0f, 0xdb, 0xa2, 0xf0, 0x38,
	0x7b, 0x43, 0x13, 0x6f, 0xc6, 0x53, 0xb9, 0xae, 0x02, 0xad, 0x8e, 0xff, 0x13, 0xf0, 0xb8, 0x40,
	0x07, 0x3c, 0x45, 0x97, 0xe1, 0x9e, 0x4f, 0xb8, 0xe0, 0x1b, 0x82, 0x6f, 0xfa, 0x84, 0x17, 0xc4,
	0x01, 0xbc, 0x14, 0x14, 0xc6, 0x68, 0xe0, 0x91, 0xcc, 0x9b, 0xd3, 0x28, 0x9c, 0x67, 0x72, 0x53,
	0x05, 0x5a, 0x0d, 0xb7, 0x37, 0x84, 0x99, 0x3d, 0x12, 0x30, 0xba, 0x09, 0xa5, 0x97, 0x24, 0x5a,
	0xd0, 0xc0, 0x3b, 0x5b, 0x59, 0xde, 0x53, 0x81, 0xd6, 0xc2, 0xed, 0x12, 0x7f, 0xfa, 0x0b, 0xee,
	0x7d, 0x05, 0x10, 0x9d, 0xf3, 0xf1, 0x50, 0xac, 0xbb, 0x09, 0x01, 0xfc, 0x73, 0x08, 0xd5, 0xed,
	0x10, 0x3a, 0xb0, 0x21, 0xec, 0x8b, 0x68, 0x6a, 0xb8, 0x6c, 0xd0, 0x55, 0xb8, 0x7f, 0x31, 0x94,
	0x16, 0xff, 0x6b, 0x1e, 0x08, 0xd6, 0x59, 0x4e, 0x13, 0x11, 0x41, 0x0b, 0x8b, 0xfa, 0xe0, 0x23,
	0x80, 0xd2, 0xc5, 0x7d, 0xd0, 0x0d, 0x78, 0xdd, 0x1a, 0xb9, 0x96, 0xed, 0x4e, 0xb1, 0x39, 0x75,
	0x46, 0xae, 0x67, 0x99, 0x63, 0xef, 0xd8, 0x9d, 0x8c, 0x6d, 0xcb, 0x39, 0x72, 0xec, 0xa1, 0x54,
	0x41, 0xd7, 0xa0, 0xbc, 0x2b, 0xb1, 0xdd, 0xa9, 0x33, 0x7d, 0x2e, 0x01, 0xd4, 0x87, 0xbd, 0x5d,
	0x76, 0x60, 0xbb, 0xf6, 0x91, 0x63, 0x39, 0xe6, 0x13, 0x6f, 0xf4, 0xcc, 0xb5, 0xb1, 0x54, 0x45,
	0x3d, 0xa8, 0xec, 0xea, 0x1e, 0x1f, 0x63, 0x67, 0x32, 0x74, 0xac, 0x02, 0x90, 0x6a, 0xdd, 0xfa,
	0xbb, 0x0f, 0x4a, 0x65, 0xf0, 0xe0, 0xcb, 0x4a, 0x01, 0xa7, 0x2b, 0x05, 0xfc, 0x58, 0x29, 0xe0,
	0xfd, 0x5a, 0xa9, 0x9c, 0xae, 0x95, 0xca, 0xf7, 0xb5, 0x52, 0x79, 0xd1, 0x3f, 0x21, 0x4b, 0xb2,
	0xa0, 0xc6, 0xd6, 0x0d, 0xbd, 0x3d, 0x7f, 0x45, 0xd9, 0x09, 0xa7, 0xe9, 0xac, 0x29, 0x7e, 0xf7,
	0xbb, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x52, 0x1f, 0x68, 0x8f, 0x6d, 0x03, 0x00, 0x00,
}

func (m *Demotion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Demotion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Demotion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.JailedValidator {
		i--
		if m.JailedValidator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.DemotedAtHeight != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.DemotedAtHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.CapBps != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.CapBps))
		i--
		dAtA[i] = 0x28
	}
	if m.GroupPowerBps != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.GroupPowerBps))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Group) > 0 {
		i -= len(m.Group)
		copy(dAtA[i:], m.Group)
		i = encodeVarintConcentration(dAtA, i, uint64(len(m.Group)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Cap != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.Cap))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintConcentration(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConcentrationGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConcentrationGroup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConcentrationGroup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Over {
		i--
		if m.Over {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.CapBps != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.CapBps))
		i--
		dAtA[i] = 0x28
	}
	if m.PowerBps != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.PowerBps))
		i--
		dAtA[i] = 0x20
	}
	if m.Power != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Group) > 0 {
		i -= len(m.Group)
		copy(dAtA[i:], m.Group)
		i = encodeVarintConcentration(dAtA, i, uint64(len(m.Group)))
		i--
		dAtA[i] = 0x12
	}
	if m.Cap != 0 {
		i = encodeVarintConcentration(dAtA, i, uint64(m.Cap))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConcentration(dAtA []byte, offset int, v uint64) int {
	offset -= sovConcentration(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Demotion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovConcentration(uint64(l))
	}
	if m.Cap != 0 {
		n += 1 + sovConcentration(uint64(m.Cap))
	}
	l = len(m.Group)
	if l > 0 {
		n += 1 + l + sovConcentration(uint64(l))
	}
	if m.GroupPowerBps != 0 {
		n += 1 + sovConcentration(uint64(m.GroupPowerBps))
	}
	if m.CapBps != 0 {
		n += 1 + sovConcentration(uint64(m.CapBps))
	}
	if m.DemotedAtHeight != 0 {
		n += 1 + sovConcentration(uint64(m.DemotedAtHeight))
	}
	if m.JailedValidator {
		n += 2
	}
	return n
}

func (m *ConcentrationGroup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Cap != 0 {
		n += 1 + sovConcentration(uint64(m.Cap))
	}
	l = len(m.Group)
	if l > 0 {
		n += 1 + l + sovConcentration(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovConcentration(uint64(m.Power))
	}
	if m.PowerBps != 0 {
		n += 1 + sovConcentration(uint64(m.PowerBps))
	}
	if m.CapBps != 0 {
		n += 1 + sovConcentration(uint64(m.CapBps))
	}
	if m.Over {
		n += 2
	}
	return n
}

func sovConcentration(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConcentration(x uint64) (n int) {
	return sovConcentration(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Demotion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConcentration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Demotion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Demotion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConcentration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConcentration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			m.Cap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cap |= ConcentrationCap(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConcentration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConcentration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Group = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupPowerBps", wireType)
			}
			m.GroupPowerBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GroupPowerBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapBps", wireType)
			}
			m.CapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CapBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemotedAtHeight", wireType)
			}
			m.DemotedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DemotedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedValidator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.JailedValidator = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConcentration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConcentration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConcentrationGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConcentration
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConcentrationGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConcentrationGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cap", wireType)
			}
			m.Cap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cap |= ConcentrationCap(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConcentration
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConcentration
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Group = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerBps", wireType)
			}
			m.PowerBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowerBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapBps", wireType)
			}
			m.CapBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CapBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Over", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Over = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConcentration(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConcentration
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConcentration(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConcentration
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConcentration
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConcentration
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConcentration
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConcentration
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConcentration        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConcentration          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConcentration = fmt.Errorf("proto: unexpected end of group")
)
