  { denom: "uyml", name: "Yamale", code: "YML", exponent: 6 },
  { denom: "uxof", name: "West African CFA franc", code: "XOF", exponent: 6 },
  { denom: "uxaf", name: "Central African CFA franc", code: "XAF", exponent: 6 },
  { denom: "ungn", name: "Nigerian Naira", code: "NGN", exponent: 6 },
  { denom: "ukes", name: "Kenyan Shilling", code: "KES", exponent: 6 },
  { denom: "uzar", name: "South African Rand", code: "ZAR", exponent: 6 },
  { denom: "ughs", name: "Ghanaian Cedi", code: "GHS", exponent: 6 },
  { denom: "uegp", name: "Egyptian Pound", code: "EGP", exponent: 6 },
  { denom: "umad", name: "Moroccan Dirham", code: "MAD", exponent: 6 },
  { denom: "udzd", name: "Algerian Dinar", code: "DZD", exponent: 6 },
  { denom: "utnd", name: "Tunisian Dinar", code: "TND", exponent: 6 },
  { denom: "uetb", name: "Ethiopian Birr", code: "ETB", exponent: 6 },
  { denom: "uugx", name: "Ugandan Shilling", code: "UGX", exponent: 6 },
  { denom: "utzs", name: "Tanzanian Shilling", code: "TZS", exponent: 6 },
  { denom: "urwf", name: "Rwandan Franc", code: "RWF", exponent: 6 },
  { denom: "uzmw", name: "Zambian Kwacha", code: "ZMW", exponent: 6 },
  { denom: "umzn", name: "Mozambican Metical", code: "MZN", exponent: 6 },
  { denom: "uaoa", name: "Angolan Kwanza", code: "AOA", exponent: 6 },
  { denom: "ubwp", name: "Botswana Pula", code: "BWP", exponent: 6 },
  { denom: "unad", name: "Namibian Dollar", code: "NAD", exponent: 6 },
  { denom: "umur", name: "Mauritian Rupee", code: "MUR", exponent: 6 },
  { denom: "ugmd", name: "Gambian Dalasi", code: "GMD", exponent: 6 },
  { denom: "ugnf", name: "Guinean Franc", code: "GNF", exponent: 6 },
  { denom: "ulrd", name: "Liberian Dollar", code: "LRD", exponent: 6 },
  { denom: "usle", name: "Sierra Leonean Leone", code: "SLE", exponent: 6 },
  { denom: "umwk", name: "Malawian Kwacha", code: "MWK", exponent: 6 },
  { denom: "umga", name: "Malagasy Ariary", code: "MGA", exponent: 6 },
  { denom: "ucdf", name: "Congolese Franc", code: "CDF", exponent: 6 },
  { denom: "usdg", name: "Sudanese Pound", code: "SDG", exponent: 6 },
  { denom: "ussp", name: "South Sudanese Pound", code: "SSP", exponent: 6 },
  { denom: "ulyd", name: "Libyan Dinar", code: "LYD", exponent: 6 },
  { denom: "usos", name: "Somali Shilling", code: "SOS", exponent: 6 },
  { denom: "udjf", name: "Djiboutian Franc", code: "DJF", exponent: 6 },
  { denom: "uern", name: "Eritrean Nakfa", code: "ERN", exponent: 6 },
  { denom: "ubif", name: "Burundian Franc", code: "BIF", exponent: 6 },
  { denom: "uscr", name: "Seychellois Rupee", code: "SCR", exponent: 6 },
  { denom: "ucve", name: "Cape Verdean Escudo", code: "CVE", exponent: 6 },
  { denom: "ustn", name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra", code: "STN", exponent: 6 },
  { denom: "ukmf", name: "Comorian Franc", code: "KMF", exponent: 6 },
  { denom: "ulsl", name: "Lesotho Loti", code: "LSL", exponent: 6 },
  { denom: "uszl", name: "Eswatini Lilangeni", code: "SZL", exponent: 6 },
  { denom: "umru", name: "Mauritanian Ouguiya", code: "MRU", exponent: 6 },
  { denom: "uzwg", name: "Zimbabwe Gold", code: "ZWG", exponent: 6 },
  { denom: "uusdc", name: "USD Coin", code: "USDC", exponent: 6 },
  { denom: "ueurc", name: "Euro Coin", code: "EURC", exponent: 6 },
