// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/alias/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the alias module.
//
// Neither field grants a power to move money: the module assigns identifiers
// and resolves them, and that is all it can do. What the second one grants is
// an exemption from the rule that every account carries a country, which is why
// it is bounded, deduplicated and governance-only.
type Params struct {
	// payload_length is how many characters an identifier carries between its
	// country prefix and its check character. Eight gives 32^8 —
	// 1,099,511,627,776 possibilities, which is eleven times the hundred billion
	// this was specified for.
	//
	// Raising it later issues longer identifiers and invalidates none of the
	// existing ones, because every alias stores its own length and the check
	// character is computed over whatever that is. Nobody will exhaust 1.1
	// trillion; the parameter exists so that a future requirement is a config
	// change rather than a migration.
	//
	// Bounded to 8..16 by Validate. Below eight the space stops being large
	// enough to be unguessable; above sixteen nobody can read it aloud, which
	// defeats the point of the module.
	PayloadLength uint32 `protobuf:"varint,1,opt,name=payload_length,json=payloadLength,proto3" json:"payload_length,omitempty"`
	// foundation_administrators are the only accounts that may hold an identifier
	// without a recorded country.
	//
	// The rule everywhere else is a refusal: no jurisdiction, no alias. These
	// accounts are the exception because they are the chain-wide authority and
	// belong to no national perimeter, so there is no country that would be true
	// of them. Their identifiers carry ZZ, which ISO 3166-1 reserves permanently
	// and will never assign to a country, so the marker cannot be mistaken for
	// one.
	//
	// Matched by exact address equality — no prefix, no pattern, no module-account
	// heuristic — because every one of those is a way for the exemption to cover
	// an account nobody meant to exempt. Validate caps the list and refuses
	// duplicates so that widening it is a visible governance act rather than an
	// append nobody reads. Empty is the default and the safe state: with no
	// administrators named, the exception grants nothing at all.
	//
	// An account here that also has a recorded country uses the country. The
	// exemption covers the absence of a jurisdiction and nothing else.
	FoundationAdministrators []string `protobuf:"bytes,2,rep,name=foundation_administrators,json=foundationAdministrators,proto3" json:"foundation_administrators,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868adbc82533099, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPayloadLength() uint32 {
	if m != nil {
		return m.PayloadLength
	}
	return 0
}

func (m *Params) GetFoundationAdministrators() []string {
	if m != nil {
		return m.FoundationAdministrators
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "blockchain.alias.v1.Params")
}

func init() { proto.RegisterFile("blockchain/alias/v1/params.proto", fileDescriptor_4868adbc82533099) }

var fileDescriptor_4868adbc82533099 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xca, 0xc9, 0x4f,
	0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xcc, 0xc9, 0x4c, 0x2c, 0xd6, 0x2f, 0x33, 0xd4,
	0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x46, 0xa8,
	0xd0, 0x03, 0xab, 0xd0, 0x2b, 0x33, 0x94, 0x12, 0x4c, 0xcc, 0xcd, 0xcc, 0xcb, 0xd7, 0x07, 0x93,
	0x10, 0x75, 0x52, 0x92, 0xc9, 0xf9, 0xc5, 0xb9, 0xf9, 0xc5, 0xf1, 0x60, 0x9e, 0x3e, 0x84, 0x03,
	0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x87, 0x88, 0x83, 0x58, 0x10, 0x51, 0xa5, 0x55, 0x8c, 0x5c,
	0x6c, 0x01, 0x60, 0x9b, 0x84, 0x54, 0xb9, 0xf8, 0x0a, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0xe2,
	0x73, 0x52, 0xf3, 0xd2, 0x4b, 0x32, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x78, 0xa1, 0xa2,
	0x3e, 0x60, 0x41, 0xa1, 0x50, 0x2e, 0xc9, 0xb4, 0xfc, 0xd2, 0xbc, 0x94, 0xc4, 0x92, 0xcc, 0xfc,
	0xbc, 0xf8, 0xc4, 0x94, 0xdc, 0xcc, 0xbc, 0xcc, 0xe2, 0x92, 0xa2, 0xc4, 0x92, 0xfc, 0xa2, 0x62,
	0x09, 0x26, 0x05, 0x66, 0x0d, 0x4e, 0x27, 0x89, 0x4b, 0x5b, 0x74, 0x45, 0xa0, 0x96, 0x3b, 0xa6,
	0xa4, 0x14, 0xa5, 0x16, 0x17, 0x07, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x07, 0x49, 0x20, 0xb4, 0x3a,
	0xa2, 0xe8, 0xb4, 0x52, 0x7a, 0xb1, 0x40, 0x9e, 0xb1, 0xeb, 0xf9, 0x06, 0x2d, 0x49, 0xa4, 0xc0,
	0xa8, 0x80, 0x06, 0x07, 0xc4, 0x85, 0x4e, 0x96, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7,
	0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c,
	0xc7, 0x10, 0x25, 0x5f, 0x99, 0x98, 0x9b, 0x98, 0x93, 0xaa, 0x8f, 0x45, 0x6f, 0x49, 0x65, 0x41,
	0x6a, 0x71, 0x12, 0x1b, 0xd8, 0xbb, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xa4, 0xf0,
	0x1d, 0x6b, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PayloadLength != that1.PayloadLength {
		return false
	}
	if len(this.FoundationAdministrators) != len(that1.FoundationAdministrators) {
		return false
	}
	for i := range this.FoundationAdministrators {
		if this.FoundationAdministrators[i] != that1.FoundationAdministrators[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FoundationAdministrators) > 0 {
		for iNdEx := len(m.FoundationAdministrators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FoundationAdministrators[iNdEx])
			copy(dAtA[i:], m.FoundationAdministrators[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.FoundationAdministrators[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.PayloadLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PayloadLength))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PayloadLength != 0 {
		n += 1 + sovParams(uint64(m.PayloadLength))
	}
	if len(m.FoundationAdministrators) > 0 {
		for _, s := range m.FoundationAdministrators {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadLength", wireType)
			}
			m.PayloadLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayloadLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FoundationAdministrators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FoundationAdministrators = append(m.FoundationAdministrators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
