#!/bin/bash
# Run this on EACH validator host, after:
#   1. Placing the coordinator's canonical-genesis.json at
#      $HOME/.blockchain/config/genesis.json (overwriting the local one from
#      01-init-node.sh)
#   2. Generating this validator's OPERATOR key in a ceremony — see below.
#
# Usage: 03-create-gentx.sh <moniker> <self-bond-amount-with-denom>
#   e.g. 03-create-gentx.sh validator-1 100000000uyml
#
# Produces a gentx-<node-id>.json file. Send this file back to the coordinator
# for step 4 (04-collect-genesis.sh).
#
# ## The operator key comes from a ceremony, not from `keys add`
#
# This step used to say "create the operator key (`blockchaind keys add
# validator`)" and leave it there. That instruction is how a chain ends up with
# the key that signs its blocks generated by a one-line command, its mnemonic
# printed to a terminal nobody was reading, and no record that it ever existed.
#
# That is not hypothetical. It is exactly what happened to this project's own
# foundation account: created by a setup script, printed once, never written
# down, and found months later sitting unencrypted in a `test` keyring on a
# cloud host — while being the address every seized asset on the chain was
# meant to be sent to. The whole key ceremony exists because of that account.
# Leaving the validator operator key to `keys add` would have repeated it for
# the key that produces every block.
#
# So: generate it with `ceremony validator`, which shows the phrase once, makes
# you read words back off the sheet before it will continue, and records only
# the public half.
#
#   ceremony validator --name "<moniker>" --armor operator.asc
#
# `--armor` writes an encrypted keystore, and the ceremony argues against it for
# a *custodian* key — a second copy of something that should have exactly one.
# For a validator operator key it is the right call, and the difference is what
# the key is for. A custodian signs a handful of proposals a year from paper. A
# validator operator signs at genesis and then whenever it edits its commission
# or unjails, so it needs to be usable by the binary without a ceremony each
# time. The paper stays the backup; the keystore is the working copy.
#
#   blockchaind keys import validator operator.asc --keyring-backend file
#
# Never the `test` backend. That backend writes the key unencrypted, which is
# what it is for — testing — and it is one `--keyring-backend` flag away from
# the arrangement described above.
#
# ## The consensus key is a different key and is NOT this one
#
# `blockchaind init` already generated it into priv_validator_key.json on this
# host, and it must never leave. `ceremony consensus` exists only to explain
# why the ceremony refuses to generate one: a consensus key that has been
# anywhere else is a consensus key that might sign two blocks at one height,
# which is the one offence that gets a validator slashed for certain.
set -euo pipefail

MONIKER="${1:?usage: 03-create-gentx.sh <moniker> <self-bond-amount>}"
AMOUNT="${2:?usage: 03-create-gentx.sh <moniker> <self-bond-amount>}"
CHAIN_ID="yamale-testnet-1"
HOME_DIR="${BLOCKCHAIND_HOME:-$HOME/.blockchain}"
KEY="${OPERATOR_KEY:-validator}"

# Refused rather than created. A missing key here means the ceremony has not
# been run, and generating one to get past this line is the entire mistake this
# step is written to prevent — the gentx would succeed, the chain would launch,
# and the operator key would have no paper behind it.
if ! blockchaind keys show "$KEY" --keyring-backend file --home "$HOME_DIR" >/dev/null 2>&1; then
  echo "error: no operator key '$KEY' in the file keyring at $HOME_DIR." >&2
  echo >&2
  echo "Generate it in a ceremony and import it — do not use 'keys add':" >&2
  echo >&2
  echo "  ceremony validator --name \"$MONIKER\" --armor operator.asc" >&2
  echo "  blockchaind keys import $KEY operator.asc --keyring-backend file --home $HOME_DIR" >&2
  echo >&2
  echo "See the comment at the top of this script for why." >&2
  exit 1
fi

# Said out loud, because the two keys are easy to conflate and the correct
# handling is opposite for each.
echo "=== operator key ==="
blockchaind keys show "$KEY" --keyring-backend file --home "$HOME_DIR" --output json |
  python3 -c 'import json,sys; k=json.load(sys.stdin); print("  ", k["name"], k["address"])'
echo "=== consensus key (stays on this host, never exported) ==="
blockchaind comet show-validator --home "$HOME_DIR"
echo

blockchaind genesis gentx "$KEY" "$AMOUNT" \
  --chain-id "$CHAIN_ID" \
  --moniker "$MONIKER" \
  --commission-rate "0.10" \
  --commission-max-rate "0.20" \
  --commission-max-change-rate "0.01" \
  --min-self-delegation "1" \
  --keyring-backend file \
  --home "$HOME_DIR"

GENTX_FILE=$(ls "$HOME_DIR"/config/gentx/gentx-*.json | head -1)
echo
echo "=== gentx created: $GENTX_FILE ==="
echo "Send this file to the coordinator (e.g. scp) for collection."
echo
echo "The operator key has done its work for now. On a deployment holding value,"
echo "take it off this host: the node needs only its consensus key to produce"
echo "blocks, and an operator key sitting on a networked machine is one"
echo "compromise away from being able to move the stake."
