// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/tokenisation/v1/tokenisation.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VerificationMode is how the chain learns what an asset sold for.
//
// The issuer alone can never set it. An issuer who under-reports steals from
// every shareholder in one transaction, at the moment of maximum value, with no
// further obligation to anybody afterwards.
type VerificationMode int32

const (
	VERIFICATION_UNSPECIFIED VerificationMode = 0
	// The appointed independent valuer signs the figure. x/oracle already holds
	// this machinery for appraisals.
	VERIFY_VALUER VerificationMode = 1
	// m-of-n attestors agree, m >= 2. Same shape as x/custody's deposits.
	VERIFY_ATTESTORS VerificationMode = 2
	// Voted, with the evidence attached to the proposal.
	VERIFY_GOVERNANCE VerificationMode = 3
	// The redemption amount was fixed when the vehicle was created -- par plus
	// coupon, on a date -- so there is nothing to appraise and nobody to trust.
	// The chain checks whether the expected amount arrived. This is the sovereign
	// case: a state issuing a bond asks its citizens to trust arithmetic rather
	// than a person.
	VERIFY_SCHEDULE VerificationMode = 4
)

var VerificationMode_name = map[int32]string{
	0: "VERIFICATION_UNSPECIFIED",
	1: "VERIFY_VALUER",
	2: "VERIFY_ATTESTORS",
	3: "VERIFY_GOVERNANCE",
	4: "VERIFY_SCHEDULE",
}

var VerificationMode_value = map[string]int32{
	"VERIFICATION_UNSPECIFIED": 0,
	"VERIFY_VALUER":            1,
	"VERIFY_ATTESTORS":         2,
	"VERIFY_GOVERNANCE":        3,
	"VERIFY_SCHEDULE":          4,
}

func (x VerificationMode) String() string {
	return proto.EnumName(VerificationMode_name, int32(x))
}

func (VerificationMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{0}
}

// Status is the vehicle's life. It ends; this is a closed-end instrument, not a
// perpetual registry.
type Status int32

const (
	STATUS_UNSPECIFIED Status = 0
	// Title exists, no shareholders yet.
	STATUS_HELD Status = 1
	// Shareholders exist. Income distributes as it arrives.
	STATUS_ACTIVE Status = 2
	// A sale price has been reported and is inside its challenge window.
	// Redemption is not open yet.
	STATUS_REPORTED Status = 3
	// The price is final. Proceeds distribute exactly like income -- the sale is
	// not a special case in the accounting, it is the last distribution and it is
	// larger.
	//
	// Transfers of the token stop here. Each token is now a claim on a known
	// fixed pot, and a pool still quoting from its reserves is a free lunch that
	// gets taken within a block.
	STATUS_REALISED Status = 4
	// Supply reached zero and the title was burned.
	STATUS_CLOSED Status = 5
	// A challenge succeeded or the sale fell through. Back to ACTIVE by
	// governance, never automatically.
	STATUS_DISPUTED Status = 6
)

var Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_HELD",
	2: "STATUS_ACTIVE",
	3: "STATUS_REPORTED",
	4: "STATUS_REALISED",
	5: "STATUS_CLOSED",
	6: "STATUS_DISPUTED",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_HELD":        1,
	"STATUS_ACTIVE":      2,
	"STATUS_REPORTED":    3,
	"STATUS_REALISED":    4,
	"STATUS_CLOSED":      5,
	"STATUS_DISPUTED":    6,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{1}
}

// Collection is a class of real-world asset the chain will record title for:
// a deeds registry, a warehouse operator's receipts, a vehicle register.
//
// Collections are chain-level constructs. There is no permissionless message
// that creates one, because a registry of deeds is not something a chain grants
// on request -- governance creates it and appoints who may mint into it.
type Collection struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The only address permitted to mint assets into this collection.
	//
	// An unset or revoked authority does not fall back to governance: the
	// collection refuses mints outright. The failure mode of a permissive default
	// here is unlimited issuance of title to things nobody owns.
	Authority string `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	// How a sale price reported against assets in this collection is checked.
	Verification VerificationMode `protobuf:"varint,3,opt,name=verification,proto3,enum=blockchain.tokenisation.v1.VerificationMode" json:"verification,omitempty"`
	// Attestor threshold when verification is VERIFY_ATTESTORS. Refused below 2:
	// one attestor is not a threshold, it is a single point of unlimited theft.
	AttestationThreshold uint32 `protobuf:"varint,4,opt,name=attestation_threshold,json=attestationThreshold,proto3" json:"attestation_threshold,omitempty"`
	// How long a reported sale price sits before redemption opens. Calibrated to
	// the asset class rather than a chain-wide constant -- a bond's redemption
	// was fixed at issuance and needs days, a unique building needs a month.
	// See docs/guides/tokenisation.md.
	ChallengeWindowSeconds int64 `protobuf:"varint,5,opt,name=challenge_window_seconds,json=challengeWindowSeconds,proto3" json:"challenge_window_seconds,omitempty"`
	// Fraction of the reported sale price a challenger must bond, in basis
	// points. Scales with the vehicle rather than being flat: a flat bond is
	// trivial for a large fraud to post and prohibitive for a small holder.
	DisputeBondBps uint32 `protobuf:"varint,6,opt,name=dispute_bond_bps,json=disputeBondBps,proto3" json:"dispute_bond_bps,omitempty"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{0}
}
func (m *Collection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return m.Size()
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Collection) GetVerification() VerificationMode {
	if m != nil {
		return m.Verification
	}
	return VERIFICATION_UNSPECIFIED
}

func (m *Collection) GetAttestationThreshold() uint32 {
	if m != nil {
		return m.AttestationThreshold
	}
	return 0
}

func (m *Collection) GetChallengeWindowSeconds() int64 {
	if m != nil {
		return m.ChallengeWindowSeconds
	}
	return 0
}

func (m *Collection) GetDisputeBondBps() uint32 {
	if m != nil {
		return m.DisputeBondBps
	}
	return 0
}

// Asset is title to one real-world thing.
//
// Title and shareholding are separate registers. This record says who owns the
// asset; the tokens say who holds the economic interest. They move
// independently, so an asset changing operator is a non-event for shareholders.
type Asset struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectionId string `protobuf:"bytes,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	// Holder of title. Whoever holds it carries the obligation to pay income into
	// the vault -- an obligation, never a balance they could walk away with.
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Uri   string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// The encumbrance. Non-empty means shareholders exist against this asset.
	//
	// It lives on the asset record rather than in an index built beside it, so
	// there is no path where a stale view sells somebody a warehouse that already
	// has shareholders. That is the failure which costs the chain its credibility
	// as a registry rather than merely costing money.
	FractionDenom string `protobuf:"bytes,5,opt,name=fraction_denom,json=fractionDenom,proto3" json:"fraction_denom,omitempty"`
	// Share of the asset's economics carried by the tokens, in basis points. The
	// sponsor keeps the rest. Fixed at fractionalisation and never editable: an
	// issuer who could revise it would dilute every holder without minting a
	// single token.
	HolderShareBps uint32 `protobuf:"varint,6,opt,name=holder_share_bps,json=holderShareBps,proto3" json:"holder_share_bps,omitempty"`
	Status         Status `protobuf:"varint,7,opt,name=status,proto3,enum=blockchain.tokenisation.v1.Status" json:"status,omitempty"`
	// The x/land parcel this vehicle is over, or 0 when the asset is not land.
	//
	// Naming the parcel is what makes the registry's authorisation enforceable:
	// fractionalising an asset with a parcel id is refused unless the registry
	// has a live permission for that parcel, the issued share is inside the
	// ceiling it set, and the sponsor is still the parcel's holder. Zero means
	// none of that applies, so a warehouse receipt or a bond is untouched.
	//
	// The parcel is referenced, never moved. Title stays in x/land held by the
	// same account, which is what keeps a fractionalised parcel governed by the
	// registry rather than by whoever accumulated the tokens.
	ParcelId uint64 `protobuf:"varint,8,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{1}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return m.Size()
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Asset) GetCollectionId() string {
	if m != nil {
		return m.CollectionId
	}
	return ""
}

func (m *Asset) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Asset) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Asset) GetFractionDenom() string {
	if m != nil {
		return m.FractionDenom
	}
	return ""
}

func (m *Asset) GetHolderShareBps() uint32 {
	if m != nil {
		return m.HolderShareBps
	}
	return 0
}

func (m *Asset) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return STATUS_UNSPECIFIED
}

func (m *Asset) GetParcelId() uint64 {
	if m != nil {
		return m.ParcelId
	}
	return 0
}

// Vault holds what is owed to shareholders and the running index that says how
// much each token has earned.
type Vault struct {
	AssetId uint64 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// Income per token, accumulated over the vehicle's life, scaled by 1e18.
	//
	// An index rather than a snapshot because a snapshot is snipeable: buy from
	// the pool at H-1, be holder of record at H, sell at H+1, and collect a
	// quarter's rent for two blocks of exposure with no capital at risk. An index
	// is time-weighted, so two blocks earn two blocks.
	//
	// It also removes a halt: there is no holder set to iterate.
	CumulativePerToken cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=cumulative_per_token,json=cumulativePerToken,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"cumulative_per_token"`
	// Total ever paid in, for the solvency view.
	Funded []types.Coin `protobuf:"bytes,3,rep,name=funded,proto3" json:"funded"`
	// The denomination income arrives in.
	Denom string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{2}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *Vault) GetFunded() []types.Coin {
	if m != nil {
		return m.Funded
	}
	return nil
}

func (m *Vault) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// Position is one account's place in the index.
//
// Settled whenever the balance moves, so what is owed is always
// balance * (cumulative_per_token - last_index).
type Position struct {
	AssetId   uint64                      `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Holder    string                      `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	LastIndex cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=last_index,json=lastIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"last_index"`
	// Settled but not yet withdrawn.
	Accrued cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=accrued,proto3,customtype=cosmossdk.io/math.Int" json:"accrued"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{3}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *Position) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

// SaleReport is a reported price inside or past its challenge window.
type SaleReport struct {
	AssetId    uint64     `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Price      types.Coin `protobuf:"bytes,2,opt,name=price,proto3" json:"price"`
	Reporter   string     `protobuf:"bytes,3,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportedAt time.Time  `protobuf:"bytes,4,opt,name=reported_at,json=reportedAt,proto3,stdtime" json:"reported_at"`
	// Opens redemption once passed, absent a dispute.
	ClaimableAt time.Time `protobuf:"bytes,5,opt,name=claimable_at,json=claimableAt,proto3,stdtime" json:"claimable_at"`
	// Attestors who have signed this figure, when the mode requires them.
	Attestors []string `protobuf:"bytes,6,rep,name=attestors,proto3" json:"attestors,omitempty"`
	Disputed  bool     `protobuf:"varint,7,opt,name=disputed,proto3" json:"disputed,omitempty"`
}

func (m *SaleReport) Reset()         { *m = SaleReport{} }
func (m *SaleReport) String() string { return proto.CompactTextString(m) }
func (*SaleReport) ProtoMessage()    {}
func (*SaleReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_22837b8d1076d960, []int{4}
}
func (m *SaleReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SaleReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SaleReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SaleReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaleReport.Merge(m, src)
}
func (m *SaleReport) XXX_Size() int {
	return m.Size()
}
func (m *SaleReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SaleReport.DiscardUnknown(m)
}

var xxx_messageInfo_SaleReport proto.InternalMessageInfo

func (m *SaleReport) GetAssetId() uint64 {
	if m != nil {
		return m.AssetId
	}
	return 0
}

func (m *SaleReport) GetPrice() types.Coin {
	if m != nil {
		return m.Price
	}
	return types.Coin{}
}

func (m *SaleReport) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

func (m *SaleReport) GetReportedAt() time.Time {
	if m != nil {
		return m.ReportedAt
	}
	return time.Time{}
}

func (m *SaleReport) GetClaimableAt() time.Time {
	if m != nil {
		return m.ClaimableAt
	}
	return time.Time{}
}

func (m *SaleReport) GetAttestors() []string {
	if m != nil {
		return m.Attestors
	}
	return nil
}

func (m *SaleReport) GetDisputed() bool {
	if m != nil {
		return m.Disputed
	}
	return false
}

func init() {
	proto.RegisterEnum("blockchain.tokenisation.v1.VerificationMode", VerificationMode_name, VerificationMode_value)
	proto.RegisterEnum("blockchain.tokenisation.v1.Status", Status_name, Status_value)
	proto.RegisterType((*Collection)(nil), "blockchain.tokenisation.v1.Collection")
	proto.RegisterType((*Asset)(nil), "blockchain.tokenisation.v1.Asset")
	proto.RegisterType((*Vault)(nil), "blockchain.tokenisation.v1.Vault")
	proto.RegisterType((*Position)(nil), "blockchain.tokenisation.v1.Position")
	proto.RegisterType((*SaleReport)(nil), "blockchain.tokenisation.v1.SaleReport")
}

func init() {
	proto.RegisterFile("blockchain/tokenisation/v1/tokenisation.proto", fileDescriptor_22837b8d1076d960)
}

var fileDescriptor_22837b8d1076d960 = []byte{
	// 1032 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x16, 0xf5, 0x65, 0x69, 0xfc, 0x11, 0x66, 0x5f, 0x39, 0x90, 0x95, 0x17, 0xb2, 0xa1, 0xa2,
	0x85, 0x90, 0xd6, 0x54, 0xed, 0xf4, 0x0b, 0x3d, 0x55, 0x1f, 0x4c, 0x42, 0x40, 0xb5, 0x05, 0x52,
	0x56, 0xd1, 0x5e, 0x88, 0x15, 0xb9, 0x96, 0x08, 0x53, 0x5c, 0x81, 0xbb, 0xb2, 0xe3, 0x7f, 0x50,
	0xa0, 0x97, 0xfc, 0x80, 0xde, 0x7a, 0xe9, 0x0f, 0xc8, 0xbd, 0xd7, 0x1c, 0x83, 0x1c, 0x8a, 0xa2,
	0x87, 0xb4, 0xb0, 0xff, 0x40, 0x8f, 0x3d, 0x16, 0xbb, 0x5c, 0xc9, 0xb2, 0x8b, 0x3a, 0x69, 0x6f,
	0x9c, 0x67, 0x9e, 0x99, 0xd9, 0x79, 0x76, 0x67, 0x08, 0xbb, 0xc3, 0x90, 0x7a, 0x27, 0xde, 0x18,
	0x07, 0x51, 0x83, 0xd3, 0x13, 0x12, 0x05, 0x0c, 0xf3, 0x80, 0x46, 0x8d, 0xd3, 0xbd, 0x6b, 0xb6,
	0x31, 0x8d, 0x29, 0xa7, 0xa8, 0x72, 0x45, 0x37, 0xae, 0xb9, 0x4f, 0xf7, 0x2a, 0x5b, 0x1e, 0x65,
	0x13, 0xca, 0x5c, 0xc9, 0x6c, 0x24, 0x46, 0x12, 0x56, 0x29, 0x8d, 0xe8, 0x88, 0x26, 0xb8, 0xf8,
	0x52, 0xe8, 0xf6, 0x88, 0xd2, 0x51, 0x48, 0x1a, 0xd2, 0x1a, 0xce, 0x8e, 0x1b, 0x3c, 0x98, 0x10,
	0xc6, 0xf1, 0x64, 0xaa, 0x08, 0xd5, 0x24, 0x49, 0x63, 0x88, 0x19, 0x69, 0x9c, 0xee, 0x0d, 0x09,
	0xc7, 0x7b, 0x0d, 0x8f, 0x06, 0xea, 0x34, 0xb5, 0x9f, 0xd2, 0x00, 0x6d, 0x1a, 0x86, 0xc4, 0x13,
	0x67, 0x40, 0x1b, 0x90, 0x0e, 0xfc, 0xb2, 0xb6, 0xa3, 0xd5, 0x8b, 0x76, 0x3a, 0xf0, 0xd1, 0x27,
	0x50, 0xc4, 0x33, 0x3e, 0xa6, 0x71, 0xc0, 0xcf, 0xcb, 0x69, 0x01, 0xb7, 0xca, 0xaf, 0x9e, 0xef,
	0x96, 0xd4, 0xd1, 0x9a, 0xbe, 0x1f, 0x13, 0xc6, 0x1c, 0x1e, 0x07, 0xd1, 0xc8, 0xbe, 0xa2, 0xa2,
	0x1e, 0xac, 0x9d, 0x92, 0x38, 0x38, 0x0e, 0x3c, 0xd9, 0x5b, 0x39, 0xb3, 0xa3, 0xd5, 0x37, 0xf6,
	0x3f, 0x30, 0xfe, 0xb9, 0x77, 0x63, 0xb0, 0xc4, 0xff, 0x92, 0xfa, 0xc4, 0xbe, 0x96, 0x01, 0x3d,
	0x84, 0x4d, 0xcc, 0xb9, 0xe8, 0x4d, 0x98, 0x2e, 0x1f, 0xc7, 0x84, 0x8d, 0x69, 0xe8, 0x97, 0xb3,
	0x3b, 0x5a, 0x7d, 0xdd, 0x2e, 0x2d, 0x39, 0xfb, 0x73, 0x1f, 0xfa, 0x0c, 0xca, 0xde, 0x18, 0x87,
	0x21, 0x89, 0x46, 0xc4, 0x3d, 0x0b, 0x22, 0x9f, 0x9e, 0xb9, 0x8c, 0x78, 0x34, 0xf2, 0x59, 0x39,
	0xb7, 0xa3, 0xd5, 0x33, 0xf6, 0xbd, 0x85, 0xff, 0x2b, 0xe9, 0x76, 0x12, 0x2f, 0xaa, 0x83, 0xee,
	0x07, 0x6c, 0x3a, 0xe3, 0xc4, 0x1d, 0xd2, 0xc8, 0x77, 0x87, 0x53, 0x56, 0xce, 0xcb, 0x4a, 0x1b,
	0x0a, 0x6f, 0xd1, 0xc8, 0x6f, 0x4d, 0x59, 0xed, 0xc7, 0x34, 0xe4, 0x9a, 0x8c, 0x11, 0xbe, 0x24,
	0x5e, 0x56, 0x8a, 0xf7, 0x0e, 0xac, 0x7b, 0x0b, 0x69, 0xdd, 0xc0, 0x4f, 0x04, 0xb4, 0xd7, 0xae,
	0x40, 0xcb, 0x47, 0x06, 0xe4, 0xe8, 0x59, 0x44, 0x62, 0x29, 0xd1, 0x6d, 0xea, 0x26, 0x34, 0xa4,
	0x43, 0x66, 0x16, 0x07, 0xb2, 0xeb, 0xa2, 0x2d, 0x3e, 0xd1, 0xbb, 0xb0, 0x71, 0x1c, 0xe3, 0xa4,
	0x88, 0x4f, 0x22, 0x3a, 0x91, 0xad, 0x15, 0xed, 0xf5, 0x39, 0xda, 0x11, 0xa0, 0xe8, 0x48, 0x68,
	0x42, 0x62, 0x97, 0x8d, 0x71, 0x4c, 0x96, 0x3b, 0x4a, 0x70, 0x47, 0xc0, 0xad, 0x29, 0x43, 0x9f,
	0x43, 0x5e, 0x28, 0x39, 0x63, 0xe5, 0x15, 0x79, 0x6d, 0xb5, 0xdb, 0xae, 0xcd, 0x91, 0x4c, 0x5b,
	0x45, 0xa0, 0xfb, 0x50, 0x9c, 0xe2, 0xd8, 0x23, 0xa1, 0xe8, 0xb7, 0x20, 0xa5, 0x28, 0x24, 0x80,
	0xe5, 0xd7, 0x7e, 0xd6, 0x20, 0x37, 0xc0, 0xb3, 0x90, 0xa3, 0x2d, 0x28, 0x60, 0xa1, 0x99, 0xbb,
	0x10, 0x6c, 0x45, 0xda, 0x96, 0x8f, 0x3c, 0x28, 0x79, 0xb3, 0xc9, 0x2c, 0xc4, 0x3c, 0x38, 0x25,
	0xee, 0x94, 0xc4, 0xae, 0x2c, 0xa9, 0x5e, 0xdf, 0xde, 0x8b, 0xd7, 0xdb, 0xa9, 0x5f, 0x5f, 0x6f,
	0xdf, 0x4f, 0x34, 0x62, 0xfe, 0x89, 0x11, 0xd0, 0xc6, 0x04, 0xf3, 0xb1, 0xd1, 0x25, 0x23, 0xec,
	0x9d, 0x77, 0x88, 0xf7, 0xea, 0xf9, 0x2e, 0x28, 0x09, 0xad, 0x88, 0xdb, 0xe8, 0x2a, 0x5d, 0x8f,
	0xc4, 0x7d, 0x91, 0x0c, 0x7d, 0x0a, 0xf9, 0xe3, 0x59, 0xe4, 0x13, 0xbf, 0x9c, 0xd9, 0xc9, 0xd4,
	0x57, 0xf7, 0xb7, 0x0c, 0x15, 0x20, 0xe6, 0xc4, 0x50, 0x73, 0x62, 0xb4, 0x69, 0x10, 0xb5, 0xb2,
	0xa2, 0xa2, 0xad, 0xe8, 0xa8, 0x04, 0xb9, 0x44, 0xe3, 0xe4, 0x02, 0x12, 0xa3, 0xf6, 0x87, 0x06,
	0x85, 0x1e, 0x65, 0x81, 0x7c, 0xa9, 0xb7, 0xf4, 0xf6, 0x21, 0xe4, 0x13, 0xad, 0xdf, 0x38, 0x4b,
	0x8a, 0x87, 0x7a, 0x00, 0x21, 0x66, 0xdc, 0x0d, 0x22, 0x9f, 0x3c, 0x55, 0x6f, 0xe4, 0x3f, 0x68,
	0x50, 0x14, 0x49, 0x2c, 0x91, 0x03, 0x99, 0xb0, 0x82, 0x3d, 0x2f, 0x9e, 0x91, 0x64, 0x74, 0x8a,
	0xad, 0xf7, 0x55, 0xba, 0xcd, 0xbf, 0xa7, 0xb3, 0x22, 0x7e, 0x23, 0xd1, 0x3c, 0xb6, 0xf6, 0x67,
	0x1a, 0xc0, 0xc1, 0x21, 0xb1, 0xc9, 0x94, 0xc6, 0xb7, 0x5e, 0xe8, 0xc7, 0x90, 0x9b, 0xc6, 0x81,
	0x47, 0x64, 0xcf, 0x6f, 0x21, 0x75, 0xc2, 0x46, 0x1f, 0x41, 0x21, 0x96, 0xb9, 0xdf, 0x62, 0x36,
	0x16, 0x4c, 0x64, 0xc2, 0xaa, 0xfa, 0xf6, 0x5d, 0xcc, 0x65, 0x87, 0xab, 0xfb, 0x15, 0x23, 0x59,
	0x93, 0xc6, 0x7c, 0x4d, 0x1a, 0xfd, 0xf9, 0x9a, 0x6c, 0x15, 0x44, 0xcd, 0x67, 0xbf, 0x6d, 0x6b,
	0x36, 0xcc, 0x03, 0x9b, 0x1c, 0x3d, 0x86, 0x35, 0x2f, 0xc4, 0xc1, 0x04, 0x0f, 0x43, 0x22, 0xf2,
	0xe4, 0xfe, 0x45, 0x9e, 0xd5, 0x45, 0x64, 0x93, 0xcb, 0x05, 0x2a, 0x37, 0x13, 0x8d, 0xc5, 0xb8,
	0x65, 0xde, 0xb0, 0x40, 0xe7, 0x54, 0x54, 0x81, 0x82, 0xda, 0x33, 0xbe, 0x9c, 0xc2, 0x82, 0xbd,
	0xb0, 0x1f, 0x7c, 0xa7, 0x81, 0x7e, 0x73, 0x5b, 0xa2, 0xff, 0x43, 0x79, 0x60, 0xda, 0xd6, 0x23,
	0xab, 0xdd, 0xec, 0x5b, 0x87, 0x07, 0xee, 0xd1, 0x81, 0xd3, 0x33, 0xdb, 0xd6, 0x23, 0xcb, 0xec,
	0xe8, 0x29, 0x74, 0x17, 0xd6, 0xa5, 0xf7, 0x6b, 0x77, 0xd0, 0xec, 0x1e, 0x99, 0xb6, 0xae, 0xa1,
	0x12, 0xe8, 0x0a, 0x6a, 0xf6, 0xfb, 0xa6, 0xd3, 0x3f, 0xb4, 0x1d, 0x3d, 0x8d, 0x36, 0xe1, 0xae,
	0x42, 0x1f, 0x1f, 0x0e, 0x4c, 0xfb, 0xa0, 0x79, 0xd0, 0x36, 0xf5, 0x0c, 0xfa, 0x1f, 0xdc, 0x51,
	0xb0, 0xd3, 0x7e, 0x62, 0x76, 0x8e, 0xba, 0xa6, 0x9e, 0xad, 0x64, 0xbf, 0xfd, 0xa1, 0x9a, 0x7a,
	0xf0, 0xbd, 0x06, 0xf9, 0x64, 0x09, 0xa0, 0x7b, 0x80, 0x9c, 0x7e, 0xb3, 0x7f, 0xe4, 0xdc, 0xa8,
	0x7e, 0x07, 0x56, 0x15, 0xfe, 0xc4, 0xec, 0x76, 0x74, 0x4d, 0x1c, 0x47, 0x01, 0xcd, 0x76, 0xdf,
	0x1a, 0x98, 0x7a, 0x5a, 0x54, 0x50, 0x90, 0x6d, 0xf6, 0x0e, 0xed, 0xbe, 0xd9, 0x49, 0xca, 0x2e,
	0xc0, 0x66, 0xd7, 0x72, 0xcc, 0x8e, 0x9e, 0x5d, 0x0a, 0x6e, 0x77, 0x0f, 0x05, 0x94, 0x5b, 0xe2,
	0x75, 0x2c, 0xa7, 0x77, 0x24, 0x82, 0xf3, 0xc9, 0xf1, 0x5a, 0x5f, 0xbc, 0xb8, 0xa8, 0x6a, 0x2f,
	0x2f, 0xaa, 0xda, 0xef, 0x17, 0x55, 0xed, 0xd9, 0x65, 0x35, 0xf5, 0xf2, 0xb2, 0x9a, 0xfa, 0xe5,
	0xb2, 0x9a, 0xfa, 0xe6, 0xbd, 0x73, 0x3c, 0xc1, 0x21, 0x69, 0x2c, 0xfd, 0xbe, 0x9f, 0x5e, 0xff,
	0x81, 0xf3, 0xf3, 0x29, 0x61, 0xc3, 0xbc, 0xbc, 0xed, 0x87, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x05, 0x6e, 0xdc, 0xe8, 0x07, 0x00, 0x00,
}

func (m *Collection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Collection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Collection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DisputeBondBps != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.DisputeBondBps))
		i--
		dAtA[i] = 0x30
	}
	if m.ChallengeWindowSeconds != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.ChallengeWindowSeconds))
		i--
		dAtA[i] = 0x28
	}
	if m.AttestationThreshold != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.AttestationThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.Verification != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.Verification))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Asset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Asset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Asset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ParcelId != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.ParcelId))
		i--
		dAtA[i] = 0x40
	}
	if m.Status != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.HolderShareBps != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.HolderShareBps))
		i--
		dAtA[i] = 0x30
	}
	if len(m.FractionDenom) > 0 {
		i -= len(m.FractionDenom)
		copy(dAtA[i:], m.FractionDenom)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.FractionDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CollectionId) > 0 {
		i -= len(m.CollectionId)
		copy(dAtA[i:], m.CollectionId)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.CollectionId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Funded) > 0 {
		for iNdEx := len(m.Funded) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funded[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTokenisation(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.CumulativePerToken.Size()
		i -= size
		if _, err := m.CumulativePerToken.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenisation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AssetId != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Accrued.Size()
		i -= size
		if _, err := m.Accrued.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenisation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.LastIndex.Size()
		i -= size
		if _, err := m.LastIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenisation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0x12
	}
	if m.AssetId != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SaleReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaleReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SaleReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Disputed {
		i--
		if m.Disputed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Attestors) > 0 {
		for iNdEx := len(m.Attestors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Attestors[iNdEx])
			copy(dAtA[i:], m.Attestors[iNdEx])
			i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Attestors[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ClaimableAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ClaimableAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTokenisation(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ReportedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ReportedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTokenisation(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.Reporter) > 0 {
		i -= len(m.Reporter)
		copy(dAtA[i:], m.Reporter)
		i = encodeVarintTokenisation(dAtA, i, uint64(len(m.Reporter)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTokenisation(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.AssetId != 0 {
		i = encodeVarintTokenisation(dAtA, i, uint64(m.AssetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTokenisation(dAtA []byte, offset int, v uint64) int {
	offset -= sovTokenisation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Collection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	if m.Verification != 0 {
		n += 1 + sovTokenisation(uint64(m.Verification))
	}
	if m.AttestationThreshold != 0 {
		n += 1 + sovTokenisation(uint64(m.AttestationThreshold))
	}
	if m.ChallengeWindowSeconds != 0 {
		n += 1 + sovTokenisation(uint64(m.ChallengeWindowSeconds))
	}
	if m.DisputeBondBps != 0 {
		n += 1 + sovTokenisation(uint64(m.DisputeBondBps))
	}
	return n
}

func (m *Asset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTokenisation(uint64(m.Id))
	}
	l = len(m.CollectionId)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = len(m.FractionDenom)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	if m.HolderShareBps != 0 {
		n += 1 + sovTokenisation(uint64(m.HolderShareBps))
	}
	if m.Status != 0 {
		n += 1 + sovTokenisation(uint64(m.Status))
	}
	if m.ParcelId != 0 {
		n += 1 + sovTokenisation(uint64(m.ParcelId))
	}
	return n
}

func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovTokenisation(uint64(m.AssetId))
	}
	l = m.CumulativePerToken.Size()
	n += 1 + l + sovTokenisation(uint64(l))
	if len(m.Funded) > 0 {
		for _, e := range m.Funded {
			l = e.Size()
			n += 1 + l + sovTokenisation(uint64(l))
		}
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	return n
}

func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovTokenisation(uint64(m.AssetId))
	}
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = m.LastIndex.Size()
	n += 1 + l + sovTokenisation(uint64(l))
	l = m.Accrued.Size()
	n += 1 + l + sovTokenisation(uint64(l))
	return n
}

func (m *SaleReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AssetId != 0 {
		n += 1 + sovTokenisation(uint64(m.AssetId))
	}
	l = m.Price.Size()
	n += 1 + l + sovTokenisation(uint64(l))
	l = len(m.Reporter)
	if l > 0 {
		n += 1 + l + sovTokenisation(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ReportedAt)
	n += 1 + l + sovTokenisation(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ClaimableAt)
	n += 1 + l + sovTokenisation(uint64(l))
	if len(m.Attestors) > 0 {
		for _, s := range m.Attestors {
			l = len(s)
			n += 1 + l + sovTokenisation(uint64(l))
		}
	}
	if m.Disputed {
		n += 2
	}
	return n
}

func sovTokenisation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTokenisation(x uint64) (n int) {
	return sovTokenisation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Collection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Collection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Collection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verification", wireType)
			}
			m.Verification = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Verification |= VerificationMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationThreshold", wireType)
			}
			m.AttestationThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeWindowSeconds", wireType)
			}
			m.ChallengeWindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeWindowSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeBondBps", wireType)
			}
			m.DisputeBondBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeBondBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTokenisation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenisation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Asset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Asset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Asset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FractionDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FractionDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HolderShareBps", wireType)
			}
			m.HolderShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HolderShareBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParcelId", wireType)
			}
			m.ParcelId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParcelId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTokenisation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenisation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativePerToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CumulativePerToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funded", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funded = append(m.Funded, types.Coin{})
			if err := m.Funded[len(m.Funded)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTokenisation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenisation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accrued", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Accrued.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTokenisation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenisation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SaleReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaleReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaleReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			m.AssetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reporter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reporter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ReportedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimableAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ClaimableAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenisation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenisation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestors = append(m.Attestors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disputed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Disputed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTokenisation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenisation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTokenisation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTokenisation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTokenisation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTokenisation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTokenisation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTokenisation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTokenisation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTokenisation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTokenisation = fmt.Errorf("proto: unexpected end of group")
)
