// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/paymsg/v1/payment_record.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PaymentRecord defines the PaymentRecord message.
//
// This is the camt.053-style statement entry, and it is what participants
// reconcile against, so its numbering is as unreclaimable as the message's:
// records already written decode by field number and nothing can re-encode
// them. Fields 11-13 are added while that is still cheap.
type PaymentRecord struct {
	EndToEndId             string `protobuf:"bytes,1,opt,name=end_to_end_id,json=endToEndId,proto3" json:"end_to_end_id,omitempty"`
	InstructingParticipant string `protobuf:"bytes,2,opt,name=instructing_participant,json=instructingParticipant,proto3" json:"instructing_participant,omitempty"`
	InstructedParticipant  string `protobuf:"bytes,3,opt,name=instructed_participant,json=instructedParticipant,proto3" json:"instructed_participant,omitempty"`
	Debtor                 string `protobuf:"bytes,4,opt,name=debtor,proto3" json:"debtor,omitempty"`
	Creditor               string `protobuf:"bytes,5,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Denom                  string `protobuf:"bytes,6,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount                 string `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// Kept, and kept at 8 and 9, for records written before metadata_hash
	// existed. Payments sent since carry the hash and leave these empty; nothing
	// rewrites the old ones, because a statement entry that changes after the
	// fact is not a statement entry.
	PurposeCode           string `protobuf:"bytes,8,opt,name=purpose_code,json=purposeCode,proto3" json:"purpose_code,omitempty"`
	RemittanceInformation string `protobuf:"bytes,9,opt,name=remittance_information,json=remittanceInformation,proto3" json:"remittance_information,omitempty"`
	BlockHeight           uint64 `protobuf:"varint,10,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// amount_commitment mirrors the field on MsgSendPayment. Not yet populated.
	AmountCommitment []byte `protobuf:"bytes,11,opt,name=amount_commitment,json=amountCommitment,proto3" json:"amount_commitment,omitempty"`
	// metadata_hash pins the off-chain payload this payment's ISO 20022 detail
	// was recorded in, so a party holding the payload can prove it is the one
	// the chain saw and cannot substitute another afterwards.
	//
	// The range proof that will accompany amount_commitment is deliberately not
	// stored here. It is checked once, at execution, and is worth nothing
	// afterwards — keeping kilobytes of it against every payment forever is
	// state bloat priced at one transaction fee.
	MetadataHash []byte `protobuf:"bytes,12,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
	// settlement_jurisdiction is recorded because the perimeter check has to run
	// against the payment, not against a memory of it: which authority may act on
	// this payment is a question asked long after the block that carried it.
	SettlementJurisdiction string `protobuf:"bytes,13,opt,name=settlement_jurisdiction,json=settlementJurisdiction,proto3" json:"settlement_jurisdiction,omitempty"`
}

func (m *PaymentRecord) Reset()         { *m = PaymentRecord{} }
func (m *PaymentRecord) String() string { return proto.CompactTextString(m) }
func (*PaymentRecord) ProtoMessage()    {}
func (*PaymentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b3852216ae473d4, []int{0}
}
func (m *PaymentRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PaymentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PaymentRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PaymentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRecord.Merge(m, src)
}
func (m *PaymentRecord) XXX_Size() int {
	return m.Size()
}
func (m *PaymentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRecord proto.InternalMessageInfo

func (m *PaymentRecord) GetEndToEndId() string {
	if m != nil {
		return m.EndToEndId
	}
	return ""
}

func (m *PaymentRecord) GetInstructingParticipant() string {
	if m != nil {
		return m.InstructingParticipant
	}
	return ""
}

func (m *PaymentRecord) GetInstructedParticipant() string {
	if m != nil {
		return m.InstructedParticipant
	}
	return ""
}

func (m *PaymentRecord) GetDebtor() string {
	if m != nil {
		return m.Debtor
	}
	return ""
}

func (m *PaymentRecord) GetCreditor() string {
	if m != nil {
		return m.Creditor
	}
	return ""
}

func (m *PaymentRecord) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *PaymentRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *PaymentRecord) GetPurposeCode() string {
	if m != nil {
		return m.PurposeCode
	}
	return ""
}

func (m *PaymentRecord) GetRemittanceInformation() string {
	if m != nil {
		return m.RemittanceInformation
	}
	return ""
}

func (m *PaymentRecord) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *PaymentRecord) GetAmountCommitment() []byte {
	if m != nil {
		return m.AmountCommitment
	}
	return nil
}

func (m *PaymentRecord) GetMetadataHash() []byte {
	if m != nil {
		return m.MetadataHash
	}
	return nil
}

func (m *PaymentRecord) GetSettlementJurisdiction() string {
	if m != nil {
		return m.SettlementJurisdiction
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentRecord)(nil), "blockchain.paymsg.v1.PaymentRecord")
}

func init() {
	proto.RegisterFile("blockchain/paymsg/v1/payment_record.proto", fileDescriptor_6b3852216ae473d4)
}

var fileDescriptor_6b3852216ae473d4 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0xb3, 0x90, 0x86, 0xd6, 0x49, 0x24, 0xb0, 0x4a, 0xb1, 0x38, 0xac, 0xb6, 0x70, 0x09,
	0x42, 0x4a, 0x54, 0x21, 0x84, 0xc4, 0x91, 0x0a, 0xa9, 0xe5, 0x54, 0xad, 0x38, 0x71, 0xb1, 0x1c,
	0x7b, 0xc8, 0x1a, 0x62, 0x7b, 0x65, 0xcf, 0x56, 0xe4, 0x1d, 0x38, 0xf0, 0x58, 0x1c, 0x7b, 0xe4,
	0x88, 0x92, 0x17, 0x41, 0x6b, 0x37, 0xd9, 0xe5, 0xb4, 0x3b, 0xff, 0xf7, 0xcf, 0x68, 0xe4, 0xf9,
	0xc9, 0xab, 0xe5, 0xda, 0xc9, 0xef, 0xb2, 0x12, 0xda, 0x2e, 0x6a, 0xb1, 0x31, 0x61, 0xb5, 0xb8,
	0xbd, 0x88, 0x7f, 0x60, 0x91, 0x7b, 0x90, 0xce, 0xab, 0x79, 0xed, 0x1d, 0x3a, 0x7a, 0xda, 0x59,
	0xe7, 0xc9, 0x3a, 0xbf, 0xbd, 0x78, 0xf1, 0x73, 0x48, 0xa6, 0x37, 0xc9, 0x5e, 0x46, 0x37, 0x3d,
	0x27, 0x53, 0xb0, 0x8a, 0xa3, 0xe3, 0xed, 0x47, 0x2b, 0x96, 0x15, 0xd9, 0xec, 0xa4, 0x24, 0x60,
	0xd5, 0x67, 0xf7, 0xd1, 0xaa, 0x6b, 0x45, 0xdf, 0x91, 0x67, 0xda, 0x06, 0xf4, 0x8d, 0x44, 0x6d,
	0x57, 0xbc, 0x16, 0x1e, 0xb5, 0xd4, 0xb5, 0xb0, 0xc8, 0x1e, 0x44, 0xf3, 0x59, 0x0f, 0xdf, 0x74,
	0x94, 0xbe, 0x25, 0x07, 0x02, 0xea, 0xbf, 0xbe, 0x87, 0xb1, 0xef, 0x69, 0x47, 0xfb, 0x6d, 0x67,
	0x64, 0xa4, 0x60, 0x89, 0xce, 0xb3, 0x61, 0xb4, 0xdd, 0x57, 0xf4, 0x39, 0x39, 0x96, 0x1e, 0x94,
	0x6e, 0xc9, 0x51, 0x24, 0x87, 0x9a, 0x9e, 0x92, 0x23, 0x05, 0xd6, 0x19, 0x36, 0x8a, 0x20, 0x15,
	0xed, 0x24, 0x61, 0x5c, 0x63, 0x91, 0x3d, 0x4a, 0x93, 0x52, 0x45, 0xcf, 0xc9, 0xa4, 0x6e, 0x7c,
	0xed, 0x02, 0x70, 0xe9, 0x14, 0xb0, 0xe3, 0x48, 0xc7, 0xf7, 0xda, 0xa5, 0x53, 0xd0, 0xee, 0xee,
	0xc1, 0x68, 0x44, 0x61, 0x25, 0x70, 0x6d, 0xbf, 0x3a, 0x6f, 0x04, 0x6a, 0x67, 0xd9, 0x49, 0xda,
	0xbd, 0xa3, 0xd7, 0x1d, 0x6c, 0x27, 0xc7, 0x87, 0xe7, 0x15, 0xe8, 0x55, 0x85, 0x8c, 0x14, 0xd9,
	0x6c, 0x58, 0x8e, 0xa3, 0x76, 0x15, 0x25, 0xfa, 0x9a, 0x3c, 0x49, 0x6b, 0x70, 0xe9, 0x8c, 0xd1,
	0xd8, 0x1e, 0x83, 0x8d, 0x8b, 0x6c, 0x36, 0x29, 0x1f, 0x27, 0x70, 0x79, 0xd0, 0xe9, 0x4b, 0x32,
	0x35, 0x80, 0x42, 0x09, 0x14, 0xbc, 0x12, 0xa1, 0x62, 0x93, 0x68, 0x9c, 0xec, 0xc5, 0x2b, 0x11,
	0xaa, 0xf6, 0x40, 0x01, 0x10, 0xd7, 0x10, 0x63, 0xf0, 0xad, 0xf1, 0x3a, 0x28, 0x2d, 0xe3, 0xb2,
	0xd3, 0x74, 0xa0, 0x0e, 0x7f, 0xea, 0xd1, 0x0f, 0xef, 0x7f, 0x6f, 0xf3, 0xec, 0x6e, 0x9b, 0x67,
	0x7f, 0xb7, 0x79, 0xf6, 0x6b, 0x97, 0x0f, 0xee, 0x76, 0xf9, 0xe0, 0xcf, 0x2e, 0x1f, 0x7c, 0x29,
	0x36, 0xc2, 0x88, 0x35, 0x2c, 0x7a, 0x81, 0xfb, 0xb1, 0x8f, 0x1c, 0x6e, 0x6a, 0x08, 0xcb, 0x51,
	0xcc, 0xd9, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x2f, 0x46, 0x16, 0x94, 0x02, 0x00,
	0x00,
}

func (m *PaymentRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PaymentRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PaymentRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SettlementJurisdiction) > 0 {
		i -= len(m.SettlementJurisdiction)
		copy(dAtA[i:], m.SettlementJurisdiction)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.SettlementJurisdiction)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.AmountCommitment) > 0 {
		i -= len(m.AmountCommitment)
		copy(dAtA[i:], m.AmountCommitment)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.AmountCommitment)))
		i--
		dAtA[i] = 0x5a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintPaymentRecord(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.RemittanceInformation) > 0 {
		i -= len(m.RemittanceInformation)
		copy(dAtA[i:], m.RemittanceInformation)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.RemittanceInformation)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PurposeCode) > 0 {
		i -= len(m.PurposeCode)
		copy(dAtA[i:], m.PurposeCode)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.PurposeCode)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Creditor) > 0 {
		i -= len(m.Creditor)
		copy(dAtA[i:], m.Creditor)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.Creditor)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Debtor) > 0 {
		i -= len(m.Debtor)
		copy(dAtA[i:], m.Debtor)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.Debtor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.InstructedParticipant) > 0 {
		i -= len(m.InstructedParticipant)
		copy(dAtA[i:], m.InstructedParticipant)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.InstructedParticipant)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InstructingParticipant) > 0 {
		i -= len(m.InstructingParticipant)
		copy(dAtA[i:], m.InstructingParticipant)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.InstructingParticipant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EndToEndId) > 0 {
		i -= len(m.EndToEndId)
		copy(dAtA[i:], m.EndToEndId)
		i = encodeVarintPaymentRecord(dAtA, i, uint64(len(m.EndToEndId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPaymentRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovPaymentRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PaymentRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EndToEndId)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.InstructingParticipant)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.InstructedParticipant)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.Debtor)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.Creditor)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.PurposeCode)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.RemittanceInformation)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovPaymentRecord(uint64(m.BlockHeight))
	}
	l = len(m.AmountCommitment)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	l = len(m.SettlementJurisdiction)
	if l > 0 {
		n += 1 + l + sovPaymentRecord(uint64(l))
	}
	return n
}

func sovPaymentRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPaymentRecord(x uint64) (n int) {
	return sovPaymentRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PaymentRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPaymentRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PaymentRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PaymentRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndToEndId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndToEndId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstructingParticipant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstructingParticipant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstructedParticipant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstructedParticipant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Debtor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Debtor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creditor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creditor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PurposeCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PurposeCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemittanceInformation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemittanceInformation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AmountCommitment = append(m.AmountCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.AmountCommitment == nil {
				m.AmountCommitment = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = append(m.MetadataHash[:0], dAtA[iNdEx:postIndex]...)
			if m.MetadataHash == nil {
				m.MetadataHash = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementJurisdiction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementJurisdiction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPaymentRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPaymentRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPaymentRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPaymentRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPaymentRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPaymentRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPaymentRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPaymentRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPaymentRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPaymentRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPaymentRecord = fmt.Errorf("proto: unexpected end of group")
)
