// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/netting/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// cycle_blocks is how many blocks a netting window stays open before the end
	// blocker closes it and settles the positions in it.
	//
	// Zero means netting is switched off, and it means that everywhere: no
	// obligation is ever admitted to a window, every submission settles gross,
	// and the end blocker returns before it computes anything. That reading is
	// chosen rather than treating zero as "every block", because this value is a
	// divisor — the cycle boundary is `height % cycle_blocks` — and a divisor
	// that arrives as zero from a hand-written genesis panics inside an end
	// blocker, which is not a failed transaction but a chain that will not
	// produce another block. Params.Validate() is not the guard that matters
	// here: it is one gate an operator can skip, and it has been skipped on this
	// chain before. The end blocker checks the value at the point it would
	// divide by it.
	//
	// One consequence of that reading is not obvious and is the reason it is
	// written down. Setting this to zero stops the end blocker before it closes
	// anything, so a window that is already open with positions in it never
	// settles: the obligations stay owed, the collateral behind them stays
	// committed, and the participants holding it cannot withdraw. Held slices
	// stop being retried for the same reason. Nothing is lost — setting a
	// positive value again closes the window at the next boundary — but between
	// the two proposals every participant in that window is carrying an exposure
	// with no settlement date, which is the state deferred net settlement exists
	// to avoid. Switch netting off between windows, not during one, and check
	// the current cycle's positions are empty before proposing it.
	CycleBlocks uint64 `protobuf:"varint,1,opt,name=cycle_blocks,json=cycleBlocks,proto3" json:"cycle_blocks,omitempty"`
	// denom_policies decides, per currency, what nets and what settles gross.
	//
	// A currency with no policy nets nothing: every obligation in it settles
	// gross, immediately. That is the safe direction to fail in — gross
	// settlement is what the chain does today, moves the money in the block it
	// was instructed in, and creates no interbank exposure for anyone to be left
	// holding. Netting is a deliberate governance act, taken currency by
	// currency, never a default that arrives with a new denom.
	DenomPolicies []DenomPolicy `protobuf:"bytes,2,rep,name=denom_policies,json=denomPolicies,proto3" json:"denom_policies"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_383bbc49ea9c7a57, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCycleBlocks() uint64 {
	if m != nil {
		return m.CycleBlocks
	}
	return 0
}

func (m *Params) GetDenomPolicies() []DenomPolicy {
	if m != nil {
		return m.DenomPolicies
	}
	return nil
}

// DenomPolicy is the netting rule for one currency.
type DenomPolicy struct {
	// denom is the currency this policy governs.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// gross_threshold is the amount at or above which a single obligation
	// bypasses netting and settles gross in the block it was submitted in.
	//
	// High-value items settling individually is the point rather than a
	// concession. It is how every RTGS system in the world is built, it is what
	// a supervisor expects to be able to see item by item, and it keeps the
	// largest exposures out of the deferred window entirely — the netting cycle
	// then carries only amounts whose failure nobody would call systemic.
	//
	// Zero means every amount is at or above it, so the currency settles
	// entirely gross. Same reasoning as an absent policy, and the same safe
	// direction.
	GrossThreshold cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=gross_threshold,json=grossThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"gross_threshold"`
}

func (m *DenomPolicy) Reset()         { *m = DenomPolicy{} }
func (m *DenomPolicy) String() string { return proto.CompactTextString(m) }
func (*DenomPolicy) ProtoMessage()    {}
func (*DenomPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_383bbc49ea9c7a57, []int{1}
}
func (m *DenomPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomPolicy.Merge(m, src)
}
func (m *DenomPolicy) XXX_Size() int {
	return m.Size()
}
func (m *DenomPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_DenomPolicy proto.InternalMessageInfo

func (m *DenomPolicy) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "blockchain.netting.v1.Params")
	proto.RegisterType((*DenomPolicy)(nil), "blockchain.netting.v1.DenomPolicy")
}

func init() {
	proto.RegisterFile("blockchain/netting/v1/params.proto", fileDescriptor_383bbc49ea9c7a57)
}

var fileDescriptor_383bbc49ea9c7a57 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0xca, 0xc9, 0x4f,
	0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0xcf, 0x4b, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0xd7, 0x2f,
	0x33, 0xd4, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x45, 0xa8, 0xd1, 0x83, 0xaa, 0xd1, 0x2b, 0x33, 0x94, 0x12, 0x4c, 0xcc, 0xcd, 0xcc, 0xcb, 0xd7,
	0x07, 0x93, 0x10, 0x95, 0x52, 0x92, 0xc9, 0xf9, 0xc5, 0xb9, 0xf9, 0xc5, 0xf1, 0x60, 0x9e, 0x3e,
	0x84, 0x03, 0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x87, 0x88, 0x83, 0x58, 0x10, 0x51, 0xa5, 0x45,
	0x8c, 0x5c, 0x6c, 0x01, 0x60, 0xbb, 0x84, 0x14, 0xb9, 0x78, 0x92, 0x2b, 0x93, 0x73, 0x52, 0xe3,
	0xc1, 0xb6, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x71, 0x83, 0xc5, 0x9c, 0xc0, 0x42,
	0x42, 0xfe, 0x5c, 0x7c, 0x29, 0xa9, 0x79, 0xf9, 0xb9, 0xf1, 0x05, 0xf9, 0x39, 0x99, 0xc9, 0x99,
	0xa9, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x4a, 0x7a, 0x58, 0x5d, 0xa8, 0xe7, 0x02,
	0x52, 0x1c, 0x00, 0x52, 0x5b, 0xe9, 0xc4, 0x72, 0xe2, 0x9e, 0x3c, 0x43, 0x10, 0x6f, 0x0a, 0x5c,
	0x28, 0x33, 0xb5, 0xd8, 0x4a, 0xe5, 0xc5, 0x02, 0x79, 0xc6, 0xae, 0xe7, 0x1b, 0xb4, 0xa4, 0x91,
	0x82, 0xa1, 0x02, 0x1e, 0x10, 0x10, 0x97, 0x29, 0xd5, 0x73, 0x71, 0x23, 0x99, 0x24, 0x24, 0xc2,
	0xc5, 0x0a, 0x36, 0x05, 0xec, 0x42, 0xce, 0x20, 0x08, 0x47, 0x28, 0x84, 0x8b, 0x3f, 0xbd, 0x28,
	0xbf, 0xb8, 0x38, 0xbe, 0x24, 0xa3, 0x28, 0xb5, 0x38, 0x23, 0x3f, 0x27, 0x45, 0x82, 0x09, 0x24,
	0xef, 0xa4, 0x0d, 0xb2, 0xf8, 0xd6, 0x3d, 0x79, 0x51, 0x48, 0x70, 0x14, 0xa7, 0x64, 0xeb, 0x65,
	0xe6, 0xeb, 0xe7, 0x26, 0x96, 0x64, 0xe8, 0x79, 0xe6, 0x95, 0x5c, 0xda, 0xa2, 0xcb, 0x05, 0x0d,
	0x27, 0xcf, 0xbc, 0x92, 0x20, 0x3e, 0xb0, 0x19, 0x21, 0x30, 0x23, 0xac, 0x58, 0x40, 0x0e, 0x74,
	0xb2, 0x3e, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c,
	0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xc5, 0xca, 0xc4, 0xdc,
	0xc4, 0x9c, 0x54, 0x7d, 0xac, 0xce, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0x4e, 0x62, 0x03, 0x87, 0xb4,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x34, 0x85, 0xf0, 0xea, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CycleBlocks != that1.CycleBlocks {
		return false
	}
	if len(this.DenomPolicies) != len(that1.DenomPolicies) {
		return false
	}
	for i := range this.DenomPolicies {
		if !this.DenomPolicies[i].Equal(&that1.DenomPolicies[i]) {
			return false
		}
	}
	return true
}
func (this *DenomPolicy) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DenomPolicy)
	if !ok {
		that2, ok := that.(DenomPolicy)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Denom != that1.Denom {
		return false
	}
	if !this.GrossThreshold.Equal(that1.GrossThreshold) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DenomPolicies) > 0 {
		for iNdEx := len(m.DenomPolicies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomPolicies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.CycleBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CycleBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DenomPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.GrossThreshold.Size()
		i -= size
		if _, err := m.GrossThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CycleBlocks != 0 {
		n += 1 + sovParams(uint64(m.CycleBlocks))
	}
	if len(m.DenomPolicies) > 0 {
		for _, e := range m.DenomPolicies {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *DenomPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.GrossThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CycleBlocks", wireType)
			}
			m.CycleBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CycleBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomPolicies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomPolicies = append(m.DenomPolicies, DenomPolicy{})
			if err := m.DenomPolicies[len(m.DenomPolicies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrossThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GrossThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
